### ISSUE TITLE
fulcro.ui.bootstrap3/ui-popover is incomplete.

### ISSUE THREAD

**Issue by adam-higuera** [fulcrologic/fulcro#101]
At the moment, the popover content is the hard-coded string "This is a test of a popover", and the popover title in the hard-coded string "Title".  These should be coming from props.

**Comment by awkay** [comment]
ooops. Feel free to send a PR. The bootstrap support is unfinished, and could defintely use some more tweaks :)

**Comment by awkay** [comment]
Fixed in aebabce35d82f26769b474469cb355f0dc126e00
