### ISSUE TITLE
Update project.clj to support java 9

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro#105]
See https://github.com/bhauman/lein-figwheel/issues/612#issuecomment-352954484

tl;dr:

There is a change in java 9 which causes figwheel to break if you don't concat `["--add-modules" "java.xml.bind"]` to the jvm-opts. Simply adding this will break when running on java 8, so the following can be done, lifted from the issue thread:

``` clj
:jvm-opts ~(concat
            ;; Normal JVM opts to pass in
            ["-Xmx1g"]
            ;; Java 9+ recognition, adding --add-modules. Java versions before 9
            ;; had a different version syntax where they contained '.' delimiters,
            ;; from Java 9 onwards it has a simple versioning scheme based on one
            ;; number.
            (let [version (System/getProperty "java.version")
                  [major _ _] (clojure.string/split version #"\.")]
              (if (>= (Integer. major) 9)
                ["--add-modules" "java.xml.bind"]
                [])))
```

**Comment by awkay** [comment]
Thanks. Let me think about this. I dislike having config files with this kind of mess. I'd almost rather add it to documentation (or as an option like java9 to the lein template) so he conditional logic doesn't have to be there for beginners to read.

**Comment by thheller** [comment]
CLJS has also fixed this already and will not need the flag in future versions. It just wasn't released yet.

**Comment by awkay** [comment]
I'm going to close this. Thanks for the info!

I put a note on the main README.
