### ISSUE TITLE
Anonymous functions as ref callbacks are an antipattern

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro#113]
Currently, the tests feature anonymous functions passed as ref callbacks. This is an antipattern. (Results in rerunning the ref callback on each render) The preferred way is to have the ref callback be a function bound to the class, so that it's "not a new function".

source: https://reactjs.org/docs/refs-and-the-dom.html#caveats

To this end, I've experimented with adding the function in the `Object` protocol:
```clj
(defsc SomeComponent [this _ _]
  {...
   :protocols
   [Object
    (handleRef [that node]
      ;; `this` is not in scope. source documentation states this is intentional.
      ;; `that` is `window` and not the value of `this` because we're not treating it as if it's a method invocation
     )]}
  (dom/div #js {:ref (.-handleRef this)} "foo"))
```

But I've run into a roadblock. When `(.-handleRef this)` is called (we're using field access here rather than method invocation because we want to pass the function as a value) `that` is bound to `window`. `.bind` is not a solution because that creates another function, defeating the purpose of binding the method to the class.

I'm hoping my understanding of method invocation is wrong, and that there's a simple way around this.

**Comment by awkay** [comment]
I personally don't see them as an antipattern (the docs you point to even say it should not matter, you just have to check for null); however, you could bind the function onto the instance in `componentWillMount` (I think that'll work). Then it'll remain constant through the life of that instant.
