### ISSUE TITLE
defrouter causing dropdown to fail

### ISSUE THREAD

**Issue by mandor2017** [fulcrologic/fulcro#122]
There appears to be an issue with routers and initial state normalization when using dropdowns. Attached example should demonstrate issue with the dropdown on "Screen2".

[router-issue.tar.gz](https://github.com/fulcrologic/fulcro/files/1629728/router-issue.tar.gz)

**Comment by awkay** [comment]
Subtle bug with normalization order in app state. Didn't affect devcards which is why it was missed. On clojars in 2.1.1-SNAPSHOT.

**Comment by mandor2017** [comment]
I am confirm the bug is fixed. Thank you for the quick response.
