### ISSUE TITLE
adv optimisations bug

### ISSUE THREAD

**Issue by vixns** [fulcrologic/fulcro#133]
Hi,
````
lein new fulcro my-project # say yes for demo
cd my-project
# add :pseudo-names true :pretty-print true compiler options
lein uberjar
java -jar target/my_project.jar
open http://localhost:8080
````
WSOD with this in the javascript console : 
````
(index):2485 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at $goog$inherits$$ ((index):2485)
    at $fulcro$client$dom$wrap_form_element$$ (dom.cljs:28)
    at dom.cljs:297
    at client_main.cljs:8
````
workaround: change cjlsbuild optimisation from :advanced to :simple

**Comment by awkay** [comment]
THanks, I'll have a look.

**Comment by awkay** [comment]
Cannot reproduce. My guess is your browser cache injected something stale from another compile? Not sure...I run it, go to `app2.lvh.me:8080` (which prevents caching by using a fake hostname), and it comes up and works fine.

**Comment by vixns** [comment]
I can reproduce when building with java9, java8 builds are fine.

**Comment by awkay** [comment]
Ah, then that is probably a compiler bug. I think I saw some traffic on that on the slack clojurescript channel. Don't remember what the resolution was.
