### ISSUE TITLE
tutorial throws some warnings: Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by yayitswei** [fulcrologic/fulcro#138]
I'm looking at the B_UI_Exercises.cljs devcards and getting the following warnings:

![screen shot 2018-02-06 at 11 19 37 pm](https://user-images.githubusercontent.com/217094/35903494-44dfa692-0b94-11e8-8f95-03149fcd1270.png)

**Comment by awkay** [comment]
Thanks for the report. If you plan to fix the warnings, a PR is appreciated. Otherwise, I have to prioritize things, and I don't leave issues open that I don't plan to do anything about soon.

**Comment by yayitswei** [comment]
No worries, I understand the bandwidth issue. Thanks for making fulcro! I'm really enjoying it so far. As a newbie to the library, I don't know how to fix the warnings and was worried it would prevent completion of the exercises, but if it's not page-breaking I can live with it.

**Comment by awkay** [comment]
It's a react error. Somewhere on that page is a vector, list or some other
collection of components that don't set `:key` so react can easily diff them
