### ISSUE TITLE
Create localization dev tool that lets you update translations directly in the UI

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#157]
Possibly integrate with Fulcro Inspect?

Possible implementation:

All of the translation functions funnel into the js function `fulcro.alpha.i18n/t`, so I think the easiest idea is to add a hook into `i18n/t`.

On tool open you might grab what is there, wrap it with your added functionality, and overwrite it with `set!`. You may have other ideas. Hot code reload should not be an issue because that ns should not change. (We could also add code to `t` itself to check for a hook, but since that is called a lot in a UI I prefer to keep it as light as possible. If anything I think it deserves as much optimization as possible.)

The instrumented `t` can collect strings, and emit extra DOM. Forcing a root render makes it easy to gather everything on-screen on demand.

Editing them sends a mutation to the server and updates the locale in app state, and forces a root render again.

Additionally, if a locale is loaded you can look for strings that have keys but no translation (as a tab of "missing translation").

I guess we need functionality to update PO files on disk. Technically on server-side there isn't really a requirement to use PO files at all, but since other tools work well with them it should be there. The new support makes it pretty easy to move i18n strings into a real database on the server.

The new i18n already supports putting the po files on disk (instead of in the uberjar), so that would make running this on a staging server for translators to use easy..not going to be able to write to a PO file in a resource path.

**Comment by awkay** [comment]
Any news @mitchelkuijpers ?  I don't tend to leave issues open on a repository if nothing is going to be done about them.

**Comment by mitchelkuijpers** [comment]
Whoops, I am actually working on this right now. I am sitting next to @wilkerlucio to get a first version working with just a locale switcher

**Comment by mitchelkuijpers** [comment]
I created an issue in fulcro-inspect: https://github.com/fulcrologic/fulcro-inspect/issues/37 so please feel free to close this issue. It is on it's way:

![image](https://user-images.githubusercontent.com/621140/39923091-82766fea-5522-11e8-8fdb-1baa5553786a.png)

**Comment by awkay** [comment]
Cool!
