### ISSUE TITLE
bind-query issues with new clojure map-entries (cljs 1.10+)

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro#160]
I was debugging this issue: https://github.com/fulcrologic/fulcro-inspect/issues/30 and traced it down to Fulcro, at this line: https://github.com/fulcrologic/fulcro/blob/develop/src/main/fulcro/client/primitives.cljc#L883

Before cljs 1.10, a call to `(first {:a 1})` returns `[:a 1]`, which is considered a vector, now it returns `map-entry`, check the following code to illustrate the difference:

```clojure
; cljs 1.9
(let [entry (first {:a 1})]
  (into (empty entry) entry))
; => [:a 1]

; cljs 1.10
(let [entry (first {:a 1})]
  (into (empty entry) entry))
; => (1 :a)
; this happens because (empty entry) returns nil, because entry is a map-entry and not a vector anymore
```

This change is actually documented here: https://github.com/mfikes/clojurescript-site/blob/1215b7c7e0f5aac0060ff6e1a762d1bed13a9315/content/news/2018-xx-yy-release.adoc#map-entries

So when we have a map on the bind process, it triggers the following problem:

The problem is that we can't do this: `(into {} ['(1 :a)])`, it triggers the error pointed on my original issue on inspect. It's caused because we are threating the map-entry as a list, but when do the `into` it changes it's type. So to fix that we have to detect the map entry and just return it, there is a new `map-entry?` function that does that. But then we force people to upgrade cljs.

**Comment by awkay** [comment]
I fixed that one, which broke a different thing (not sure why exactly, but fixed that as well). I tried all of my tests out against 1.10.64 and the all passed. Would be interested knowing if that fixes issues.

**Comment by awkay** [comment]
I've confirmed that without the fix I cannot even run the tests...so this seems likely to have fixed any significant issues, since that tests most of the full stack in unit form, and the test runner actually compiles under whatever cljs you have, verifying that the basics of fulcro are working in an integration sense.
