### ISSUE TITLE
FulcroRemoteI ok-handler doesn't seem to play well with df/load

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro#166]
Below is the minimal case, based off of the shadow-cljs template.
https://github.com/levitanong/load-ok-repro

Relevant bits are in `client.cljs`, specifically line 22 and below.

**Comment by awkay** [comment]
Thanks, I'll take a look. This is surprising.

**Comment by awkay** [comment]
I've verified that this is a problem, and also traced it to Fulcro Inspect. Moving this issue there.
