### ISSUE TITLE
Typo in DevelopersGuide.adoc

### ISSUE THREAD

**Issue by d4hines** [fulcrologic/fulcro#169]
I've said this before, but the docs for Fulcro rival much bigger projects, so thank you guys for the work you've put into this!

I believe there's a typo in section [2.11.4 of the Developer Guide](https://github.com/fulcrologic/fulcro/blob/master/DevelopersGuide.adoc#2114-requesting-data-from-the-alternate-remote). In the source it's line 2163. It currently reads:

```
(df/load app :posts Post {:remote :rest :target [:post-list/by-id :the-one :posts]})
```

`Post` is missing the namespace. It should read like it does in the source repo `fulcro/fulcro-getting-started`, which is:
```
(df/load app :posts root/Post {:remote :rest :target [:post-list/by-id :the-one :posts]})
```

**Comment by awkay** [comment]
Thanks, fixed.
