### ISSUE TITLE
alternative to `select *`

### ISSUE THREAD

**Issue by gdanov** [fulcrologic/fulcro#186]
Would be nice to have way to say "select *" in the query. 
I tried several options to work around it by adding variations of [:table/by-id :db/id] (with proper names of course) to the property list, hoping that would be dynamic identity look-up but it either is not supposed to work or I did not figure out the correct syntax.

**Comment by awkay** [comment]
Please use slack #fulcro for questions :)

`['*]` is supported for selecting all attributes of a node. You have to quote it or it won't compile. If you mean you want an entire table, then that is just `[[:table/by-id '_]]` (the outer vector is the query wrapper itself). Same thing on quoting.

If you mean you want to select everything from a specific entity by ID, that is a join `[{[:table/by-id id] ['*]}]`

**Comment by gdanov** [comment]
thanks a lot!
in scdef having ``:query ['*]`` causes exception about the ident missing. if I use lambda it returns all props, but normalization stops working.
tried having ``:query [:myentity/id {:children '...} {[:myentity/by-id :myentity/id] ['*]}]`` but no luck. if I change the idref to use fixed id it works well however.

p.s. I do my best to stay away from slack in my hobby time, sorry for bothering you here
