### ISSUE TITLE
Consider using `io/input-stream` instead of `io/file` when dealing with resources

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro#205]
Consider https://github.com/fulcrologic/fulcro/blob/f2d5d9e3794773b51d055a5bc463521dd120f87c/src/main/fulcro/easy_server.clj#L87

When one uberjars a server, `io/file` stops working.
`io/input-stream` works for both jars and non-jar servers.

**Comment by awkay** [comment]
fixed in 2.5.10
