### ISSUE TITLE
Load post mutation refresh doesn't honor mutation-declared refresh

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#207]
Refresh declared in mutations is not honored when run as post-mutations.  Since post mutations alter arbitrary state and we already have shouldComponentUpdate optimizations it seems like just doing a root render on post mutations might be the saner thing to do...would eliminate a lot of hassle.

The problem is: if that is too slow, then going backwards will break apps.

Seems like fixing locally declared refresh is the right thing to do. If ppl want simple workflow, use `:keyframe` render mode.

**Comment by wilkerlucio** [comment]
Can't we refresh in the same way we do for regular mutations?

**Comment by awkay** [comment]
Just saying the "way we do it for regular mutations", which allows for declaring the refresh *on* the mutation isn't working with post mutations. It is currently inconsistent.

**Comment by awkay** [comment]
We're in agreement.

**Comment by awkay** [comment]
Fixed in 2.5.10
