### ISSUE TITLE
Discoverable docs for dom macros

### ISSUE THREAD

**Issue by currentoor** [fulcrologic/fulcro#208]
Currently, when I look at the docs for dom macros in my editor I get this
```
fulcro.client.dom/div
 [& args]
  Not documented.
```

Do you think it'd be better to have something like this instead?

```
fulcro.client.dom/div
[& args]
Returns a React DOM element. Can be invoked in several ways

(div "hello")
(div nil "hello")
(div {:onClick f} "hello")
(div :#the-id.klass.other-klass "hello")
(div :#the-id.klass.other-klass {:onClick f} "hello")
```

IMO this is more discoverable, which is important since we did invent our own syntax for the DOM API.

**Comment by awkay** [comment]
Happy for a contribution that does it.
