### ISSUE TITLE
GC Support

### ISSUE THREAD

**Issue by currentoor** [fulcrologic/fulcro#216]
We need some GC support. 

We can have a function specifically for removing an ident from a list.
`(remove-ident state-map ident path)`, where `path` is the path in app state to the list, like `prim/integrate-ident`.

We can also have a function for larger GC, `(clean-ident state-map #{table-names} ident)`. This function will remove `ident` from those tables specified. 

We should have two version of each, like `integrate-ident` and `integrate-ident!`.

Maybe we also need a way to do a deep delete and remove entities across joins. Like in this function. Perhaps that should be called `deep-clean-ident`?
https://github.com/fulcrologic/fulcro-inspect/blob/develop/src/client/fulcro/inspect/helpers.cljs#L123-L140

These examples in the book should be updated after this change.
http://book.fulcrologic.com/#_handling_mutations
http://book.fulcrologic.com/#_mutations_on_a_normalized_database
http://book.fulcrologic.com/#_triggering_the_remote_mutation_from_the_client

**Comment by awkay** [comment]
Hey, small request: If you're going to open a feature issue with goals, please also include a milestone or some other kind of timeline.  I don't believe in opening issues we're not going to immediately address.  Leads to a pile of stuff that no one looks at (affectionately know in lean circles as a Jira Load :D  ).

**Comment by currentoor** [comment]
Good idea. I never heard of that term, but it does seem appropriate 😄 

How about a timeline of by the end of this week, if not middle of next week at the latest?

**Comment by awkay** [comment]
So we've identified a few categories of these:

1. Helper functions for targeted state manipulation when you *know* what you want to remove. Not really GC, but helpful. These would be functions like `remove-ident`, `delete-form-state`, etc.
2. Semi-automated GC...e.g.  `(recursive-delete some-ident)`, which delete the table entry at ident, and ALSO follows idents starting at that entity, and removes all children. This requires something like a white-list/black-list of table names, or a set of "isComponent" Datomic-like indicators to prevent unintentional traversal.
3. Fully-automated GC. The function scans entire app state removing things that are not referenced. This one also needs "help" in that unions may not be currently pointing at data that needs to be kept. 

A few helpers from (1) would be nice, especially as "mutation helpers".  (2) could be commonly useful...not sure about 3.

**Comment by awkay** [comment]
The basic remove ident and form state are in RC4.  Others are deferred for now.

**Comment by awkay** [comment]
Latest release of Fulcro has a new `normalized-state` ns that has more helpers.
