### ISSUE TITLE
Misleading Logging

### ISSUE THREAD

**Issue by currentoor** [fulcrologic/fulcro#221]
I thought my app was broken when I was trying to abort an upload request (and one of my remotes is websockets) because of this line

https://github.com/fulcrologic/fulcro/blob/develop/src/main/fulcro/client.cljc#L320

Everything was happening correctly, the upload was being successfully aborted. However, I got the error log message because websockets don't implement `FulcroRemoteI`, even though the remote that uploads files does implement it.

Maybe the error message should only happen if none of the remove implement `FulcroRemoteI`?

**Comment by awkay** [comment]
Yes, you're right. The abort has to apply to any remote that is abort capable, but there should no longer be an error there, since for the most part no one manually needs to implement a remote anyhow.
