### ISSUE TITLE
Improvements to CSS system

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#230]
Change defsc to automatically include any components that are in the query that have CSS. 

- It MUST leave any mentioned manually alone, but de-dupe

The `defrouter` should also generate the inclusion if there is css on any of the routes.

**Comment by wilkerlucio** [comment]
As discussed, we are not changing `defsc`, instead we should walk the query from root and automatically collect components to add into the CSS tree.

**Comment by awkay** [comment]
Are you planning on coding this soon?  I don't keep issues in unless we're doing something about them in the near term.

**Comment by wilkerlucio** [comment]
I want to, just very busy right now, but I think I can give it a go on the weekend

**Comment by awkay** [comment]
I've decided to give this a go.  It will include:

- [ ] Add an options argument to the CSS functions (like `style-element`) 
- [ ] Add an option for `:auto-include` that will use the query of the component to find children with CSS and automatically include them.
- [ ] Add an option for changing the default ordering between `:breadth-first` and `:depth-first`
- [ ] Make sure on `:depth-first` that the deepest version of something that appears in multiple places is the one that is used.
- [ ] Support a `:force-order [A B]` option that will cause the given elements to appear in that order within the final result. The behavior should be to the given elements to the end, but in the order described.
