### ISSUE TITLE
Combination of routing, form-state, and links produce nil entries for link references

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro#231]
- https://github.com/levitanong/repro-fulcro-form-link
- `shadow-cljs watch main`
- open up fulcro inspect
- note that there are no non-sensical entries in any of the tables
- click on "new foo form"
- `:bar/by-id` is polluted with nil entries

**Comment by awkay** [comment]
Thanks, I'll have a look as soon as I get time.

**Comment by awkay** [comment]
Fixed in 5ce7f82325b07856a78ecc3c6b04e33fefbf8b2f
