### ISSUE TITLE
defsc validation misses parameterized attributes

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro#232]
When detecting if attributes are present on the query, Fulcro seems to skip over parameterized attributes. So while this is considered valid:

```clojure
(fp/defsc SomeComponent [_ _]
  {:ident [:id :id]
   :query [:id]})
```

This is not:

```clojure
; Fulcro triggers an error saying `:id` is not present on the query
(fp/defsc SomeComponent [_ _]
  {:ident [:id :id]
   :query ['(:id {:some-param "value"})]})
```

I think we should use the AST to parse the query so we can have normalized state over details like params.

**Comment by awkay** [comment]
Can't do it...macro.  get-query won't eval

**Comment by awkay** [comment]
Actually, if you pre-processed it and changed get-query calls to `[*]` then it would process

**Comment by wilkerlucio** [comment]
We have the data for the query, I think we can call `query->ast` on it, the current issue seems to be just that it just looks for the keys but don't parse the query, so a list is not considered a valid property, that's my guess, and we don't need `get-query` for that

**Comment by awkay** [comment]
I don't think there is much more to do here. Use a lambda if you have an expression in your query.
