### ISSUE TITLE
Re-vamp book and code to stress server-side use of Pathom

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#288]
The book needs to show how to structure a more complete app with full-stack use of Pathom.  The server-side defmutation and defquery should be discouraged (dropped from docs, even).  

I don't necessarily see a need to make it a specific dependency of Fulcro's...since I'm going to stress writing your own server over the old pre-written stuff.  

Ideally this content would also include how to server EQL through lacinia for GraphQL clients.

**Comment by wilkerlucio** [comment]
I like the idea, just not sure about the Lacinia thing, instead of making it expose EQL (which I think would be a lot of work) we can teach people to use Pathom on the client connect to any GraphQL backend (that could be Lacinia or anything else), IMO will be a simpler path that already works.

**Comment by awkay** [comment]
The benefit of using EQL is that it is more powerful....I've alraedy written a layer for Lacinia that works well, and is easy to add on...that let's clients still use placeholders, etc.  The GQL stuff is just in case you need external API AFAIC.
