### ISSUE TITLE
Remove unconditional use of cljsjs.react.dom.server

### ISSUE THREAD

**Issue by thheller** [fulcrologic/fulcro#291]
The `fulcro.client.localized-dom-common` ns unconditionally requires `cljsjs.react.dom.server` in CLJS which means it will also end up in browser builds.

https://github.com/fulcrologic/fulcro/blob/54018c219086577da2ea7aa88c8bfce08bc80ca5/src/main/fulcro/client/localized_dom_common.cljc#L8

ends up including
```
node_modules/react-dom/cjs/react-dom-server.browser.production.min.js 16.68 KB
```
I'm not sure where it is actually used but it probably is not used in browser builds.

**Comment by awkay** [comment]
I know we have some users that are doing SSR in node. @claudiu-apetrei  in particular.  But I guess he is probably building with shadow...so, I'm not sure if removing that would break anyone. I agree that the majority of users won't want that.

**Comment by claudiu-apetrei** [comment]
@thheller @awkay Yes, really happy with node-js & fulcro. It's mainly due to shadow-cljs :smile:  Should not break anything for me and if something breaks on nodejs personally I'm happy to find workarounds if that means 16kb less for fulcro client apps.

**Comment by awkay** [comment]
I looked at it. Seems safe to remove.  Done.
