### ISSUE TITLE
[SSR] incorrect escapes around CSS inline scripts

### ISSUE THREAD

**Issue by nha** [fulcrologic/fulcro#299]
Server-side rendering example:
clj code: 
```(def garden-css {:font-family "\"Helvetica Neue\""})```

ends up being rendered on the sever as:
```font-family: &quot;Helvetica Neue&quot;```
which is invalid.

The above clj works fine on the client, however the client escapes the single-quote version:
- clj code ```{:font-family "'Helvetica Neue'"} ```
- single quotes become ```&#x27```

**Comment by awkay** [comment]
Same as the other one. Happy to take an SSR PR to fix these, but am not personally planning on working on it.

**Comment by awkay** [comment]
Fixed in Beta 5.

Will accept a PR against the fulcro 2 branch to back port if anyone cares to do it.
