### ISSUE TITLE
BUG: routing `:routing/pending-route ` does not get a read after dynamic route is loaded

### ISSUE THREAD

**Issue by mitchelkuijpers** [fulcrologic/fulcro#30]
If you load a dynamic route and it needs to load the module, only the query for the dynamic router get's updated and not the property `::routing/pending-route` this should get a read after a route has been loaded. The current behavior is that it will show a progress spinner indefinitely when a route has been loaded.

**Comment by awkay** [comment]
I'm not sure I understand. Do you have a minimal reproducible case? The demo that uses this works fine, and the UI updates properly.

**Comment by mitchelkuijpers** [comment]
Yes I reproduced it here: https://github.com/mitchelkuijpers/fulcro/commit/72f61338fef50f33da3ee171161ba3eee598efbb
