### ISSUE TITLE
Make form state work with React Native

### ISSUE THREAD

**Issue by mdhaney** [fulcrologic/fulcro#306]
Currently, form state requires fulcro.client.dom which requires react-dom which is of course missing on React Native.  The only thing using the dom is the FormConfig component, which is mainly just a query component, but it has rendering code so you can render it if you want (for debugging?).

I think a straightforward fix would be to remove the rendering code from FormConfig, and then have a renderable version of the component in a separate namespace.  I would be happy to create a PR once we figure out the best approach.

**Comment by awkay** [comment]
That's probably reasonable...from what I remember the rendered body isn't used for anything really...just debugging, but inspect is better.  I'm happy removing it. A PR would be great.

**Comment by mdhaney** [comment]
Well, if you're ok with removing it, that's super easy.  In fact, I've already verified that works (using the monkey patching feature in shadow-cljs).  I'll put together a PR in a bit.

**Comment by awkay** [comment]
If you send a PR I'll accept it.  I don't leave issues open that are not getting traction.

**Comment by awkay** [comment]
Actually, I'm in there working on something else...I'll just fix it.

**Comment by mdhaney** [comment]
Sorry about that - got pulled onto something else and kept meaning to swing back and put together a PR. Thanks for taking care of it.
