### ISSUE TITLE
Push updating all clients that share data?

### ISSUE THREAD

**Issue by AndrewMorsillo** [fulcrologic/fulcro#307]
Sorry if this is a nonsensical question as I am a newbie to Clojure and Fulcro.

I currently use Meteor.js for rapidly prototyping web apps. It has the nifty ability to pub/sub data to clients such that any update to a piece of data on the server will update all clients that have that piece of data loaded. No plumbing needed. This makes it super seamless and easy to write multi user react applications -- things "just work" and the UI is never out of sync with the server/DB no matter where data mutations are coming from.

Is something like that possible with Fulcro? After reading some of the docs it seems like the server could pretty easily track which queries each client has requested then send a push if a mutation touches that bit of data.

edit: I guess an easier way of saying it would be: Would it be possible to have a method like `load` but that instead sets up a subscription to the data instead of just loading it once?

IMO something like this might make a lot of sense for a framework like Fulcro. The UI is already completely derived from a normalized client side database. Why not make updates to that database generic instead of manually handling different messages from the server? From what I can understand so far it would make no difference to the UI but would eliminate a lot of plumbing code at (potentially) the cost of a bit of performance.

**Comment by awkay** [comment]
Hi, please use the slack clojurians #fulcro channel for discussion.

The short answer is "yes", with websockets it is more a matter of tracking the data on the server than difficulty on the client.
