### ISSUE TITLE
question: how to start a repl?

### ISSUE THREAD

**Issue by markx** [fulcrologic/fulcro#310]
[Here](https://github.com/fulcrologic/fulcro/blob/develop/DevelopersGuide.adoc#starting-the-server) it says:
> Simply start a REPL and use:

How do I start this REPL?
`lein repl`? `shadow-cljs clj-repl` ? `shadow-cljs cljs-repl`? None works for me.

**Comment by claudiu-apetrei** [comment]
@markx After you do `lein new fulcro app` you can checkout the README.md file in the project. It has a bit more info about running everything. 

If it still does not work, can you post what you tried and the errors youre getting ?

**Comment by awkay** [comment]
Yes, please see the README in the generated project. I'll add thta to the book.
