### ISSUE TITLE
Documentation improvement - setting up API server

### ISSUE THREAD

**Issue by drewverlee** [fulcrologic/fulcro#313]
The docs say 

> Start a LOCAL clj nREPL in IntelliJ (using IntelliJ's classpath with
> the `dev` alias selected in the Clojure Deps tab)

but using deps and using IntelliJ's classpath would seem to be two exclusive options.

**Comment by awkay** [comment]
Please use Slack for questions.

The docs are correct.  Using IntelliJ's classpath means it will use the currently selected aliases from the clojure deps settings tab.
