### ISSUE TITLE
Props can not be gathered correctly when property key is the same as ident in a join

### ISSUE THREAD

**Issue by TimovanderKamp** [fulcrologic/fulcro#336]
I think I found a bug in fulcro (3.0.0). I noticed that my props in a component weren't correct and found a way to reproduce it.

```
(defsc Example [this props]
  {:query [:data
           :id]
   :initial-state (fn [_]
                    {:id :my-id
                     :data :important})
   :ident [:example :id]} (1)
  (dom/div))

(defsc Root [this props]
  {:initial-state (fn [_]
                    {:example (comp/get-initial-state Example {})})
   :query [{:example (comp/get-query Example)}]} (2)
  (dom/div))
```

The component `Example` has an ident that starts with the key `:example`, see (1).
The component `Root` has a join for property `:example` with the query from the component `Example`, see (2).

Root's props are now incorrect:
```
{:example {}}
```

This can be fixed by changing the property `:example` in `Root` to something else or when the key `:example` in `Example`'s ident is changed to something else.

```
{:example-that-works {:data :important, :id :my-id}}
```

So it seems that `{:example [:example :my-id]}` does not work because the keys are the same.

**Comment by awkay** [comment]
This is not a bug, it is a minor annoyance of the fact that root nodes are aligned with the root of the database. You should namespace your keywords to avoid accidental collision.

For example, your root query keys should be something like `:root/example` and the table name should follow a convention like `:example/id` (which assists with pathom usage as well).

**Comment by TimovanderKamp** [comment]
Ah that totally makes sense as it is trying to store the ident and the denormalized data at `:example` in the db. Thanks for the explanation.
