### ISSUE TITLE
Duplicated idents when using tempids with targeting

### ISSUE THREAD

**Issue by MrEbbinghaus** [fulcrologic/fulcro#345]
While using tempids I am getting duplicated entries, when targeting the mutation-join.

I suspect that the problem is that I have the ident with the tempid in my list and the new ident with the new realid is not recognized as a duplicate. 

```clojure
(defmutation add-todo [{:keys [todo]}]
  (action [{:keys [state]}]
    (swap! state mrg/merge-component Todo todo :prepend [:all-todos]))
  (remote [env] true
    (-> env
        (m/with-target (targeting/prepend-to [:all-todos]))
        (m/returning Todo))))

; The transaction: 
(todoish.models.todo/add-todo
 {:todo
  {:todo/id #fulcro/tempid["292e3ba6-93d0-472c-af7c-d303e7d89ad9"],
   :todo/task "My first task", 
   :todo/done? false}})

; Network response:
{todoish.models.todo/add-todo
 {:tempids {#fulcro/tempid["292e3ba6-93d0-472c-af7c-d303e7d89ad9"] 0},
  :todo/id 0, 
  :todo/task "My first task", 
  :todo/done? false}}

; The db afterwards
{:all-todos [[:todo/id 0] [:todo/id 0]],
 :todo/id {0 {:todo/id 0, :todo/task "My first Task", :todo/done? false}}}

```

**Comment by awkay** [comment]
You gave it a local ID of zero (your local action prepended the literal ident with id 0), then you told it to prepend it again in post processing.
What do you expect to happen?

**Comment by MrEbbinghaus** [comment]
I expected it to behave like it would, if I didn't use a tempid.

In most cases I write my mutations in such a way that merge twice. Once in action and once after the remote is done. In case the remote would do some modification. 
Is there something wrong with this?

**Comment by MrEbbinghaus** [comment]
Ah I understand what your point is. 

Returning them is ok, but re-adding them to the list is not.
