### ISSUE TITLE
:refresh key in load! config doesn't seem to do anything

### ISSUE THREAD

**Issue by TimovanderKamp** [fulcrologic/fulcro#347]
It seems like the load config key `:refresh` is not working anymore. I found that the function `com.fulcrologic.fulcro.data-fetch/load-params*` also ignores the config key.

**Comment by awkay** [comment]
You're right...it was meant to move into the transact from params...but I overlooked it, and the new rendering refresh has made it mostly unnecessary...but just *mostly* :)

**Comment by awkay** [comment]
Please try 3.0.7-SNAPSHOT

**Comment by TimovanderKamp** [comment]
Thanks, I will try it out and let you know about it!

**Comment by TimovanderKamp** [comment]
I can confirm that this issue has been resolved.

**Comment by awkay** [comment]
Thanks

Fixed in 3.0.8
