### ISSUE TITLE
defsc missing @constructor jsdoc

### ISSUE THREAD

**Issue by thheller** [fulcrologic/fulcro#348]
With CLJS `1.10.597` some unnecessary function wrappers are no longer created (CLJS-3077) which means the Closure Compiler now processes things a bit more efficiently. As a side-effect it started warning about

```
------ WARNING #3 -  -----------------------------------------------------------
 Resource: com/fulcrologic/fulcro/algorithms/form_state.cljc:81:26
 dangerous use of 'this' in static method com.fulcrologic.fulcro.algorithms.form_state.FormConfig
--------------------------------------------------------------------------------
------ WARNING #4 -  -----------------------------------------------------------
 Resource: shadow/cljs/ui/app.cljs:39:26
 dangerous use of 'this' in static method shadow.cljs.ui.app.MainNavBuild
--------------------------------------------------------------------------------
------ WARNING #5 -  -----------------------------------------------------------
 Resource: shadow/cljs/ui/app.cljs:208:26
 dangerous use of 'this' in static method shadow.cljs.ui.app.MainNav
--------------------------------------------------------------------------------
...
```

which is every use of `defsc`.

The warnings should go away if you change

https://github.com/fulcrologic/fulcro/blob/8a7b99300435e91e222ac20e6e8d6d64afe7d7d9/src/main/com/fulcrologic/fulcro/components.cljc#L1249

to

```clojure
(defonce ~(vary-meta sym assoc :doc doc :jsdoc ["@constructor"])
```

This tells the Closure Compiler that this is an actual constructor function and use of `this` is "safe".

Can make a PR if you want.

**Comment by awkay** [comment]
Thanks for the tip, I can get it.

**Comment by awkay** [comment]
Deployed in 3.0.11-RC3
