### ISSUE TITLE
fs/entity->pristine* no longer working 

### ISSUE THREAD

**Issue by bsifou** [fulcrologic/fulcro#349]
entity->pristine*  stopped working from version 3.0.2 to 3.0.3 (it works like expected in all versions prior to 3.0.2).  It no longer affect the client db by copying the actual values to the map config under :pristine key.

**Comment by awkay** [comment]
I'm actively using the function, and I'm not aware of any breakage.  3.0.3 is definitely not the latest version...do you have a failing test???

**Comment by bsifou** [comment]
If you try the video series example (the one in youtube) with the tag `rendering-part-2` (https://github.com/fulcrologic/video-series/tree/rendering-part-2). It doesn't actually do anything when running (fs/entity->pristine*)  as (fs/dirty? props) returns always true. Even after just running it. I hope this helps.

**Comment by awkay** [comment]
I do not see a problem.  The tests are all passing, and I even expanded them.  The logic is working fine, and it is in active use in RAD, so I think you are misunderstanding something. Please submit a repro case if you insist there is an error.
