### ISSUE TITLE
namespace of `computed` keyword is still fulcro 2 style

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro#362]
https://github.com/fulcrologic/fulcro/blob/fa79f904c2e23437a3431d5feadcfad38f986aea/src/main/com/fulcrologic/fulcro/components.cljc#L139

Perhaps it should be renamed to `::computed`.

**Comment by wilkerlucio** [comment]
Doing that now would be a breaking change, so I guess this will stay as is.

**Comment by levitanong** [comment]
Fair enough.

**Comment by awkay** [comment]
Yep...`:tempids` also suffers from that.  I had to break ppl enough from 2->3, that those just didn't matter.
