### ISSUE TITLE
initLocalState using configure-component! seems to not be working

### ISSUE THREAD

**Issue by felipethome** [fulcrologic/fulcro#373]
I'm trying to create a component dynamically using `com.fulcrologic.fulcro.components/configure-component!`. Everything works fine except for :initLocalState which is not being executed:

```clj
(def Something
  (c.comp/component
    {:ident          (fn [_ props]
                       [:customer/id (:customer/id props)])
     :query          (fn [this]
                       [:customer/id
                        :customer/phone])
     :initLocalState (fn [this props]
                       (js/console.log "localState")
                       {:a (fn [] (js/console.log "a"))})
     :css            [[:.container {:background "red"}]]
     :render         (fn [this]
                       (js/console.log "state" (comp/get-state this))
                       (dom/div :.container "Hi!"))}))
```

`localState` is never printed and `comp/get-state` returns undefined.

`:initLocalState` seems to be in the generated class:

![Screen Shot 2020-02-14 at 13 49 39](https://user-images.githubusercontent.com/4316501/74550902-f5dac080-4f30-11ea-95f3-eca5d8387a4c.png)

Maybe we are missing something when using configure-component!, if that is the case can you please point me to the right direction?

**Comment by awkay** [comment]
You are missing something. That function requires you understand the internals, and does *no* magic for you.  React has *no* initLocalState. The *function* passed to that is the React constructor. Please use #fulcro in Slack for support.
