### ISSUE TITLE
Support more content types?

### ISSUE THREAD

**Issue by carrete** [fulcrologic/fulcro#379]
It seems that Fulcro only supports its own middleware for handling content negotiation, and thus is limited to only Transit encoded requests and responses. Fulcro's Transit middleware uses the `:transit-params` key to store decoded params in the request map instead of merging with `:params`. This means other middleware, like ring-middleware-format or its successor https://github.com/metosin/muuntaja/, and other content types, like EDN, cannot be used with Fulcro.

What would it take, and would it be welcomed, to modify Fulcro so that other middleware and other content types could be supported? I'd like to be able to type curl requests on the command-line to our Fulcro api endpoint, and the lack of EDN, which is much easier to type than Transit, complicates this.

**Comment by awkay** [comment]
That's a simple-enough add (the middleware is very very small.  So if you want to add it, that's fine.
