### ISSUE TITLE
Standardize transit usage

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#400]
Fulcro has a transit ns that adds tempid support.  Ideally there would be a clear interface for setting all of the various extensions you want (i.e. local dates, etc.) so that the standard API can have them enabled and encode/decode them properly.

On the client-side, placing these in the app itself seems reasonable. I would also want to check the server-side API and make it easy to use the same CLJC code to install the handler via the middleware with as little friction as possible.

**Comment by awkay** [comment]
Added global transit registry, and then made str conversion, http remote, and websocket remote all use it.

**Comment by awkay** [comment]
- [ ] Make sure server HTTP middleware uses registry in standard wrappers
- [ ] Check websocket server and client middleware for the same...I think I only did one side

**Comment by awkay** [comment]
Hm. The central registry isn't "great". I've moved this to a branch, and want to analyze the solution a bit more before pushing this forward.  The main trouble I was having was more to do with unifying RAD stuff, so perhaps the transit standardization should more go there.

**Comment by awkay** [comment]
Further consideration. When I have time to finish this:

- [ ] Allow the transit extensions to just be defined as a map
- [ ] Allow the map of transit extensions to be installable into remotes, RAD, etc.

This does require a manual intervention step to expand transit support, but the central registry has several problems: 1. side-effect nature of it leads to fragile code. 2. More than one app on a page might disagree on registry (extremely rare, but possible).

**Comment by awkay** [comment]
Existing work is on the transit branch. The registry bit needs to be dumped, but otherwise the code there is useful/good.

**Comment by awkay** [comment]
It would also be nice if the clojure(script) reader were simultaneously (but optionally) extended so you could define reader and writers that would handle `#mytype "thing"`

**Comment by wilkerlucio** [comment]
I think having the global registry is ok, as you said, the biggest risk is disagreement on the register. But would be nice if an app could override it (maybe some setting when building the app), so if the app wants "transit isolation", it gets it. We could use the map definition at the app configuration part.

I think Fulcro Inspect should also be able to leverage this configuration on the user encoding side, this can allow the DB tab to show the tagged types (altough it can't decode it).

**Comment by michaelwhitford** [comment]
I think the global registry would be acceptable.  I don't think I'd remember to pass things around everywhere, and would constantly have to go back and fill in the blanks to get things working.  Using a config flag to turn it on or off might be good to cover all use cases.

**Comment by currentoor** [comment]
I think the benefits of a global registry out weigh the costs. I'd rather have one place to declare all my custom types, which should be namespaced anyway.

To have issues you'd have to have two apps in the same page that also disagree on the definition of the same type right? You could fix that by having two different types `#v1/bigdecimal "..."` and `#v2/bigdecimal "..."`. Or put one of the apps in an iframe?

How would the inspect tool access this registry?

**Comment by awkay** [comment]
@currentoor Inspect would not access the registry...it's an external thing with its own build. That said, the default handler in Inspect is OK with custom transit types. It just shows their tag and their internal rep, which is always a ground type like string or something.  So, the preload in your app can encode them using this registry, but inspect itself won't be able to share that encoding. I'm not bootstrapping cljs in Inspect :) 

I tend to agree that the two apps on one page is fixable..you'll be in control of at least one of them, right? I  don't expect random users in the ecosystem to be embedding random Fulcro apps via a js script tag in custom HTML.

**Comment by awkay** [comment]
@currentoor @wilkerlucio On Inspect: It occurs to me that transit types end up being encoded in "ground types". (perhaps you already realized this Wilker)  This means that only the application needs to know what they *mean*, but Inspect can still support them better than I thought:

If the default handler *preserves* their tag, and the ground type supports pr-str/read-string, then I should be able to invent transit support and cljs readers for the thing on the fly in Inspect itself.

Say they encode Java LocalDate (which has the CLJC joda time impl) with tag `time/local-date`, and with a rep of "2020-01-22".  In Inspect, I can see the rep is a string.  So, if they use `time/local-date` as their transit tag, I think we can also install a cljs reader that would then support reading that in the Query tab, and I can make up the transit types (can you do that at runtime in js? I think so) that implements the transit bits and uses their tag/rep, so I should be able to properly encode it as transit.  I'll have to try it out and see if that works.

**Comment by awkay** [comment]
Hm, actually, transit already does this:

```
(def test-writer #?(:cljs (ft/writer)))
(def dump-writer #?(:cljs (t/writer :json {})))
#?(:cljs
   (defn a []
     (let [encoded (t/write test-writer [1 (Cruft. 43)])
           decoded (t/read (tolerant-reader) encoded)]
       (t/write dump-writer decoded))
     ))
```

The encoded thing uses a writer that knows how to encode, so I can encode the Cruft object. The reader is just a default reader, which it turns out will tolerate any value transit value and encode it like this:

```
[1 #object[Transit$TaggedValue [TaggedValue: test/cruft 43]]]
```

which a "dumb" writer with nothing configured can turn back into the correct on-the-wire rep:

```
"[1,[\"~#test/cruft\",43]]"
```

Thus, any sort of "proxy thing" like Inspect that just holds the values can do so as long as it carefully serializes/deserializes the Transit$TaggedValue into whatever medium it might use for long-term storage.

```

**Comment by awkay** [comment]
- [ ] Create extensible transit registry
- [ ] Update internal http remote to support it
- [ ] Update fulcro-websockets to support it
- [ ] Update RAD to support it
- [ ] Update transit string conversion functions in fulcro's libs to support it

**Comment by currentoor** [comment]
Oh wow that's awesome! Good find!

**Comment by awkay** [comment]
In 3.3.6
