### ISSUE TITLE
Query transforms do not preserve pre-merge semantics

### ISSUE THREAD

**Issue by RokLenarcic** [fulcrologic/fulcro#409]
Here I am talking about code shown in the Developer Manual http://book.fulcrologic.com/#_pre_merge_basics

In this example the key `:ui/count` is initialized by pre-merge hook to be `{:ui/count 5}`.

It is not mentioned in the Manual that this only works incidentally, because `:ui/count` is a simple value that requires no normalization. This same approach doesn't work for `fs/form-config-join` for instance.

To be more concrete:

Let's take the component from the manual and add form state to it. The resulting component query is:

`[::counter-id ::counter-label :ui/count fs/form-config-join]`

When issuing a load to the server, the UI centric data get's elided from the query by the default (which is what we want), so the server gets query:

`[::counter-id ::counter-label]`

Server returns some data and our pre-merge hook is called. 

And here's the issue: any data our pre-merge hook returns will be normalized with the new, after-elision, query. So whatever we return besides `::counter-id` and `::counter-label` from the pre-merge hook will be merged into state as-is.

In the example in the manual, it makes no difference to `:ui/count 5` whether normalization works or not. But when you try to add form config to incoming data:

```
(merge current-normalized
       (fs/add-form-config Countdown data-tree))
```

it breaks, throwing errors because form state gets added unnormalized. 

To me this seems like a broken feature, because it only works for the simple case, and it is not clear (nor explained in the docs) why adding form config in pre-merge doesn't work (it requires quite a bit of debugging to figure it out). So even if this is intended behaviour it lack clarity.

It feels to me that adding UI centric data to incoming data in a component focused, component local fashion is what pre-merge was made for, but normalizing only properties that were queried to server kills the whole thing. The workaround of turning off eliding of UI centric properties isn't too hot either.

**Comment by awkay** [comment]
@wilkerlucio do you remember the aspects of this with respect to query transform?  I thought we were using the pre-elision query here, but perhaps it got changed for some other competing reason?  I'll look at the current logic.

**Comment by awkay** [comment]
So, @RokLenarcic I agree with you that this isn't ideal.  There are three competing features colliding in this particular code location:

* You can transform the query in `load!` itself.
* You can use the global transform to change the query (elide nodes).
* The remote code itself can change the query to match the data (advanced feature that might not be the best idea now...was originally added for file upload progress, but could also be used to merge alternate error data into the db).

So, the load completion code is required to use the modified query if it exists, or the general promises of the load API fail; however, as you note if you've eliminated bits of the query for data you'd like to be considered in the merge you're also going to have a problem.

The quick workaround at the moment is to move the elision of things to the network request middleware layer, which is really where it should be in hindsight, and not use the global EQL transform or load query transform for removing form config.

**Comment by awkay** [comment]
Ah, actually I broke this as far as the book is concerned by changing the default global EQL transform to elide fulcro-related things from the query (routing and forms).

**Comment by RokLenarcic** [comment]
I know this is not easy to solve, as you obviously want to merge using the query after the transform (since transform can be arbitrary, not just eliding things), but at the same time I'd like to merge joined things, that I elided because the server doesn't need them.

**Comment by RokLenarcic** [comment]
Seems to be fixed... perhaps adding a test to prevent regressions would be wise.

**Comment by RokLenarcic** [comment]
My initial assessment was wrong, this didn't fix the issue, I just misread the log statements. 
The query in pre-merge still lacks the elided parts and it will not normalize them if you supply them.

**Comment by awkay** [comment]
not sure how that's possible. I literally changed the query it uses for merge to be the one in the load...so unless you're eliding it at load instead of globally, it should be right now.

**Comment by RokLenarcic** [comment]
I will try to make a minimal project demonstrating this... give me a day or so.

**Comment by awkay** [comment]
I wrote a quick example app with the following form:

```
(defsc Form [this {:form/keys [name] :as props}]
  {:query         [:form/id :form/name fs/form-config-join]
   :ident         :form/id
   :initial-state {:form/id   1
                   :form/name "Sam"}
   :form-fields   #{:form/name}
   :pre-merge     (fn [{:keys [data-tree]}]
                    (fs/add-form-config Form data-tree))}
  (dom/div
    (dom/button {:onClick #(df/load! this [:form/id 42] Form)} "Load!")
    (dom/label "Name")
    (dom/input {:value    name
                :onChange #(m/set-string! this :form/name :event %)})))
```

I push the button to run the load, and see this in the network tab:

```
[{[:form/id 42] [:form/id :form/name]}]
```

notice it has elided the form config join on the network. My response from the server is:

```
{[:form/id 42] {:form/id 42, :form/name "Sam"}}
```

The pre-merge takes effect, and I see this in app state:

For path `[:form/id 42]`:

```
{:form/id 42,
 :form/name "Sam",
 :com.fulcrologic.fulcro.algorithms.form-state/config
 [:com.fulcrologic.fulcro.algorithms.form-state/forms-by-ident
  {:table :form/id, :row 42}]}
```

and the form config is correctly normalized at the ident 
`[:com.fulcrologic.fulcro.algorithms.form-state/forms-by-ident
  {:table :form/id, :row 42}]`

This is the functionality I expect on the full-stack case. I do not see a problem with the latest snapshot release.
