### ISSUE TITLE
Synchronous xact should allow app as a "no render" option

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#414]
This is useful when you're using fulcro to control something (i.e. data model of d3) so you only need data model updates.

**Comment by awkay** [comment]
@fjolne actually, it does allow that, it just issues a warning, which I think is still a good idea. If you choose to use it that way, it is OK. The warning is for when someone uses it and wonders why they didn't get a UI refresh.

**Comment by fjolne** [comment]
@awkay yes, it actually issues only a warning if called like this (which is a bit awkward):
```clojure
(comp/transact! app
    [(f)]
    {:synchronous? true})
```
but `transact!!` itself has an `log/error` check on top of that, so this would issue an error _and_ a warning
```clojure
(comp/transact!! app
    [(f)])
```
![Screenshot 2020-05-27 at 11 44 52](https://user-images.githubusercontent.com/42907266/82998155-0b6f8400-a010-11ea-9798-88d8d4a7bbae.png)

**Comment by fjolne** [comment]
The checks are essentially the same:
```clojure
; comp/transact!!
(when-not (and (component? component) (has-ident? component))
     (log/error ,,,))
```
```clojure
; tx-processing/transact-sync!
(if (and component (comp/component? component) (comp/has-ident? component))
  ,,,
  (log/warn ,,,))
```
so I think it makes sense to remove `log/error`.
