### ISSUE TITLE
Form State Support documentation is outdated

### ISSUE THREAD

**Issue by zilti** [fulcrologic/fulcro#418]
As the title says. Also, a loooooot of stuff is missing. Example: in 19.4. Submitting Data: `com.fulcrologic.fulcro.mutations/returning` is being used, but it is being used with 3 args instead of the allowed 2, and it isn't described anywhere what this function expects to get back from the server.

**Comment by awkay** [comment]
Thanks for letting me know. I am aware that the book needs a lot of updates. I simply don't have the time right now.  I'll get to it when I get to it.
