### ISSUE TITLE
Snag Following the book

### ISSUE THREAD

**Issue by sittim** [fulcrologic/fulcro#429]
I am following the book and I hit the snag:

```
Build Status
X Compilation failed.
The required JS dependency "react" is not available, it was required by "cljsjs/react.cljs".

Dependency Trace:
	app/client.cljs
	com/fulcrologic/fulcro/application.cljc
	com/fulcrologic/fulcro/data_fetch.cljc
	com/fulcrologic/fulcro/algorithms/tx_processing.cljc
	com/fulcrologic/fulcro/mutations.cljc
	com/fulcrologic/fulcro/components.cljc
	cljsjs/react.cljs

Searched for npm packages in:
	/home/sporty/clojure/app/node_modules

See: https://shadow-cljs.github.io/docs/UsersGuide.html#npm-install
```

This happens on the first `$ npx shadow-cljs server` command.  Granted it is not hard to fix, the last line of the error listing above gives the instructions, nevertheless, it makes the reader wonder if he is doing something wrong.

![image](https://user-images.githubusercontent.com/8825037/94141136-4e186000-fe3a-11ea-8cf2-c26900ce0c4a.png)

**Comment by awkay** [comment]
If you read a few small sections up (Create your project), it tells you to install those things:

$ npm install shadow-cljs react react-dom --save

**Comment by sittim** [comment]
Thank you, I did miss that.
