### ISSUE TITLE
Since versioning update, state isn't being communicated to the dom via transact! mutation.

### ISSUE THREAD

**Issue by AlbertSnows** [fulcrologic/fulcro#430]
For simplicity I recreated this using the first example from the book through the fulcro template repo, but a different simple mutation is what prompted the search. I've had this issue since upgrading to 3.3.3, but I upgraded from 3.3.1 if I recall correctly. 
Suppose we have this section of code to work with:
```
(defmutation bump-number [ignored]
  (action [{:keys [state]}]
    (swap! state update :ui/number inc)))

(defsc Root [this {:ui/keys [number]}]
  {:query         [:ui/number]
   :initial-state {:ui/number 0}}
  (dom/div
    (dom/h4 "This is an example.")
    (dom/button {:onClick #(comp/transact! this `[(bump-number {})])}
      "You've clicked this button " number " times.")))
```
In our application we'll get the corresponding button and text. 
![image](https://user-images.githubusercontent.com/17283162/94222539-421cb480-feb3-11ea-9981-b58c6d95f082.png)

Via our mutation we should expect to see the number on the button increment via `inc` 
However, I haven't been able to reproduce this in the dom. 
Instead, the state that fulcro manages updates but the dom isn't respecting the change. We can see this through inspect. 
![image](https://user-images.githubusercontent.com/17283162/94223058-9aa08180-feb4-11ea-9d28-3a46c9b9ea54.png)
So while the button will continue to show 0, the dom will increment as expected. 
I haven't tested between different versions to narrow down the cause yet, but I at least wanted this made so that, in the meantime, it's available in the likely event I'm merely making a mistake.

**Comment by awkay** [comment]
Such a trivial app, and no problems I can see. I'm using bleeding edge ahead of this and I'm not seeing problems. What version of React and other NPM deps are you using?

**Comment by awkay** [comment]
I switched to 3.3.3 in Fulcro itself, built that program, and it runs fine. Not sure what is going on for you.

**Comment by awkay** [comment]
Please use #fulcro in Slack for support.  I use Fulcro in more than 1 production project every day. If something this trivial was broken it would have never made it to release :)
