### ISSUE TITLE
is [com.fulcrologic.fulcro.components :as comp] needed?

### ISSUE THREAD

**Issue by sittim** [fulcrologic/fulcro#432]
In the book in the section 3.5.4, there seems to be a need for one more require:

![image](https://user-images.githubusercontent.com/8825037/94364116-02152780-0095-11eb-8db0-d05e1d576c46.png)

I added:

```
[com.fulcrologic.fulcro.components :as comp]
```
now it compiles.  I am very new to this, so I can be missing something.

**Comment by awkay** [comment]
Thanks. That was a recent add and I didn't look at the requires.

**Comment by sittim** [comment]
Very well, there is so much detail, its easy to miss.  Just trying to help vetting.
