### ISSUE TITLE
Fulcro 2.0: Drop ILocalState

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#44]
Verify that this is an unused feature...pretty sure it is. Love to hear from people on their thoughts about it. I'm leaning towards deleting it from the system altogether. I just don't see it fitting in the picture very well.

**Comment by awkay** [comment]
It is usable, but not sure how to proceed. IMHO I think that it isn't needed. It is meant to give you an external way to save component local state. The only thing you can really index by is component instance, so that is useless for history. I think I'm going to relegate this to the scrap pile, but possibly at a later date.

**Comment by currentoor** [comment]
I can confirm that I've never used this, I even forgot it existed.

**Comment by awkay** [comment]
I'm going to go ahead and leave it, but consider it deprecated.
