### ISSUE TITLE
`comp/get-query` of component with `:use-hooks? true` returns `nil` in CLJ

### ISSUE THREAD

**Issue by fjolne** [fulcrologic/fulcro#443]
```clojure
(defsc Comp [this props]
  {:query [:item]})

(defsc CompWithHooks [this props]
  {:query      [:item]
   :use-hooks? true})

;; CLJ (not CLJS)
(comp/get-query Comp) ;; => [:item]
(comp/get-query CompWithHooks) ;; => nil
```

**Comment by awkay** [comment]
CLJ support should be considered very rough. I don't use it, and almost no one else does. I have no time for these tasks. If you want to address them, you're welcome to try...but for the moment I do not plan to fix.

**Comment by fjolne** [comment]
sure, no problem, i’ll try to fix if it becomes crucial, just bookkeeping.

**Comment by MrEbbinghaus** [comment]
I think this is because `comp/add-hook-options!` is not implemented for clj

**Comment by awkay** [comment]
Well, if you really think about the whole thing use-hooks should proably just be ignored in CLJ...there's no hooks API, after all. The fix is to just make the macro ignore the option for CLJ I think.
