### ISSUE TITLE
Fulcro 2.0: Shared is not kept in history

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#45]

**Comment by awkay** [comment]
Shared is a thing I've avoided using. My general opinion of it is still kind of on the fence, and it makes history serialization a problem at the moment. I'd be interested in any comments that people would like to share about their experience with it here, so I can decide what to do with it in 2.0

**Comment by mitchelkuijpers** [comment]
We only use it for constants which we mainly use to make it easy to implement SSR because then you want to initialize the globals per request.

**Comment by awkay** [comment]
I think I'm going to leave shared out of the history story for now. Consider it incompatible with full history support. I may deprecate it in the future. Let's see what other things pop up around it to see if it is really needed.
