### ISSUE TITLE
:initLocalState not hot-reloading

### ISSUE THREAD

**Issue by helins-io** [fulcrologic/fulcro#451]
Hi,

As discussed on Slack, I seem to encounter a weird behavior regarding `:initLocalState`. Essentially, once it has been defined on a component, it never hot reloads when modified, in spite of the file being of course recompiled. In other words, instances created _after_ modifying `:initLocalState` in any way still call the old code. Everything else hot reloads as expected.

This repro case is a hello world example based on the project I am currently working on. What you can do is modify the code located in `:initLocalState` after launching the dev build and notice how the new code is ignored when creating new instances:

https://github.com/helins-io/fulcro.initLocalState

I expect there is something wrong with my config but I really cannot find it out... Probably something very basic I'll be ashamed of when it is discovered.

Best,
Adam

**Comment by awkay** [comment]
Fixed in 3.4.13-SNAPSHOT.  Should not affect anything else.
This just affects hot code reload, and of course only affects new instances.
