### ISSUE TITLE
Breaking change in v3.4.13-SNAPSHOT

### ISSUE THREAD

**Issue by helins-io** [fulcrologic/fulcro#452]
Resolving issue #451 unfortunately resulted in a breaking change. It seems `this` in `:initLocalState`  is not the same as when rendering.

It is useful to leverage `this` for efficiently caching things like lambdas directly on the object without polluting the component state and this is now impossible since you loose anything prepared in ´:initLocalState`. And quite a few more things actually. Overall it not the intuitive that the reference to a component changes. Unless it is impossible to do otherwise implementation-wise, I would strongly advice against because it makes you uncertain about extending Fulcro (which is a big deal about Fulcro as I understand it).

Then it is true that `:initLocalState` is about the state. However it `this` is unreliable, it should not be passed as an argument but that would be a massive breaking change certainly no one wants.

**Comment by awkay** [comment]
Hm, Im not sure why the code change I made would cause `this` to stop working correctly. I don't think it particularly hard to have to force reload to get initLocalState to refresh. I'll just revert the change. It is used so little in most FUlcro programs as to be a non-issue, and I do not want a breaking change.
