### ISSUE TITLE
Use latest guardrails with fix for spec-crash when using datomic

### ISSUE THREAD

**Issue by avocade** [fulcrologic/fulcro#457]
The issue in expound was fixed in 0.8.7 which was imported in this commit to guardrails:

https://github.com/fulcrologic/guardrails/pull/17

Is there a reason fulcro is still using a very old version of guardrails (0.0.12)?

https://github.com/fulcrologic/fulcro/blob/7b4f0351e64bb99d6573f1227a380c61815a556f/deps.edn#L9

**Comment by awkay** [comment]
Just haven't updated the internal dep is all.
