### ISSUE TITLE
union query + placeholders can lead to a confusing edge case

### ISSUE THREAD

**Issue by tmoerman** [fulcrologic/fulcro#458]
The following code snippet illustrates an edge case when using a union query in combination with Pathom [placeholders](https://blog.wsscode.com/pathom/v2/pathom/2.2.0/core/placeholders.html), to break up the query into sub-queries while maintaining context.

```
(ns acme.fruit.fulcro-merge-edge-case-test
  "Captures an Fulcro merge algorithm edge case."
  (:require
   [clojure.test :refer [deftest]]
   [cljs.test :refer-macros [deftest testing is use-fixtures]]
   [fulcro-spec.core :refer [specification provided behavior assertions]]
   [com.fulcrologic.fulcro.algorithms.merge :as merge]
   [com.fulcrologic.fulcro.components :as comp :refer [defsc]]

   [taoensso.timbre :as log]))

(defn ->fruit-ident
  [props]
  (cond
    (-> props :acme.apple/id merge/nilify-not-found some?) [:acme.apple/id (:acme.apple/id props)]
    (-> props :acme.orange/id merge/nilify-not-found some?) [:acme.orange/id (:acme.orange/id props)]
    :else (log/error "Cannot derive a valid ident." props)))

(defsc AppleState [_ _]
  {:query [:acme.apple/id
           :acme.fruit/state]
   :ident :acme.apple/id})

(defsc Apple [_ _]
  {:query [:acme.apple/id
           :acme.fruit/name
           ;; :acme.fruit/state -> not queried here but under the :>/extra placeholder
           {:>/extra (comp/get-query AppleState)}]
   :ident :acme.apple/id})

(defsc Orange [_ _]
  {:query [:acme.orange/id
           :acme.fruit/name
           :acme.fruit/state]
   :ident :acme.orange/id})

(defsc FruitUnion
  "Union query component for different Fruit types."
  [this props]
  {:query (fn [] {:acme.orange/id (comp/get-query Orange)
                  :acme.apple/id  (comp/get-query Apple)})
   :ident (fn [] (->fruit-ident props))})


(deftest reproducing-the-bug

  (behavior "Reproduce situation where the :acme.fruit/state of the Apple instance doesn't show up in the Fulcro DB"
    ;; Captured by logging data-tree in pre-merge of FruitUnion
    (let [data-tree [{:acme.apple/id    "apple-id-1"
                      :acme.fruit/name  "Granny Smith"
                      :acme.fruit/state ::merge/not-found
                      :>/extra          {:acme.apple/id    "apple-id-1"
                                         :acme.fruit/state "fresh"}}
                     {:acme.orange/id   "orange-id-1"
                      :acme.fruit/name  "Clementine",
                      :acme.fruit/state "rotten"}]]

      (assertions

        "Show that :acme.fruit/state isn't merged for the Apple instance"
        (merge/merge-component {} FruitUnion data-tree) =>
        {:acme.apple/id  {"apple-id-1" {:acme.apple/id   "apple-id-1"
                                        :acme.fruit/name "Granny Smith"
                                        ;;:acme.fruit/state "fresh" ;; <== EXPECTED
                                        :>/extra         [:acme.apple/id "apple-id-1"]}}

         :acme.orange/id {"orange-id-1" {:acme.orange/id   "orange-id-1"
                                         :acme.fruit/name  "Clementine"
                                         :acme.fruit/state "rotten"}}}

        ))))
```
* To understand the edge case, consider the `Apple` component: it specifies `:acme.apple/id`, `:acme.fruit/name` in the top-level query, and uses a placeholder `:>/extra` to "push down" another property `:acme.fruit/state` to the `AppleState` component, which also normalizes the data using the same ident as `Apple`.
* A similar component `Orange` queries everything in the top-level.
* Both `Apple` and `Orange` are combined using a union query component `FruitUnion`.

So far so good.

Now, when merging some server data, resolved by some server logic (using Pathom), we observe that the `:acme.fruit/state` field is not merged into the Fulcro DB. 

A note on the `data-tree`: in the top-level of the map for "apple-id-1" instance, the `:acme.fruit/state` has value `::merge/not-found`. I captured this by logging the data-tree in `pre-merge` on the Union in my real-world project from which this example is derived. I'm guessing Fulcro combines the query props of  both `Apple` and `Orange` in the data-tree during normalization, which would explain the ::merge/not-found value in the top-level of the "apple-id-1" instance as it is not queried top-level in the `Apple` component.

**The issue**: the placeholder with component `AppleState` **does** query `:acme.apple/state`, however: this field and its value are not normalized into the final result (marked with EXPECTED in the test).

This issue can easily be fixed by adding the `acme.fruit/state` to the `Apple` query as well but was a bit confusing to debug, hence this report for future reference.

Thoughts?
Thanks.

**Comment by awkay** [comment]
What was the *actual* query sent to Pathom, and what did it return. Log these at the server so you don't get a value that has already been messed with by various bits of Fulcro.

**Comment by awkay** [comment]
I'm closing this. I don't plan on doing anything about it. If you find it is important to you and want to attempt a PR, please feel free to do so.
