### ISSUE TITLE
Version 3.5 Improvements

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#467]
I've been wanting to do some further improvements related to UI composition for Fulcro 3.5. This issues is here to track the desired behaviors, and discuss them. The basic list is:

- [x] Able to give a root an ident, so it doesn't have to be co-located with the root of the data graph (roots can live in a table)
- [x] Floating roots are more prominent, and are easier to use. See below.
- [x] Supply an interop factory that makes a floating root easier to use from vanilla js, and one that makes it easier to use from other cljs libraries. For example, translates js props into cljs Fulcro props.

The surface API would not be significant in look. I think one improvement might look something like this:

```
(defsc MyThing [this props]
  {:query [...]
   :ident (fn [] [:root/id ::MyThing]) ; root CAN have an ident, so lives in a table
   :root? true} ; marks this as a root, so factory auto-detects how to build it
  normal dom stuff)
```

such that the factory generator would auto-detect that this was a floating root, and generate the right kind of factory for it. 

An additional improvement for pure react Interop would be to make a variant of `use-fulcro` so that hooks are usable from pure functions:

```
(defn MyThing [this]
  (let [fulcro-props (use-fulcro APP this {:query ... :ident ...})] ...))
```

or something similar. The raw function would act like a low-level plain Hooks component (this has raw js props). This would allow Fulcro components (or apps) to live inside of a pre-existing React app of any kind.

The main challenge with this is that namespaces like Dynamic Routing rely on introspection of the query to find nested routers, and any root boundary, by definition, isn't composed in query or data. So, routing becomes "floating root" centric. This is both a documentation concern and an issue for beginners and experienced people alike.

**Comment by awkay** [comment]
@wilkerlucio let me know if you have some other ideas

**Comment by wilkerlucio** [comment]
I really like the `use-fulcro` idea, having the ability to just pull data as hooks from Fulcro state will be awesome!

**Comment by awkay** [comment]
After doing various bit of development experiments on this, it seems like it would be quite possible to separate Fulcro from  React in a way that would allow wider usage. The `alpha.raw` ns has shown an initial pattern of non-react usage, but the hard linkage to React in components and application make a hard requirement for React.

It isn't terribly difficult to split the two, just a decent amount of (fairly tedious) work.
