### ISSUE TITLE
Fix templates and book to recommend Pathom setting for always returning :tempids

### ISSUE THREAD

**Issue by holyjak** [fulcrologic/fulcro#484]
Add :tempids to mutation join queries by default so that all users do not need to do that themselves (and '* if there was no query before to preserve Pathom's behavior of everything the whole mutation output if the user did not ask for anything in particular).

Add ::p/errors to all queries and mutations - most users of Fulcro use Pathom and need this and an extra keyword will not harm those who don't (and they can always remove it via a custom global transform).

Also expand the default elision [list to RAD's](https://github.com/fulcrologic/fulcro-rad/blob/7db67fbab7211dcaa87658fb35c0165d7eb322fa/src/main/com/fulcrologic/rad/application.cljc#L25) (for the sake of simplicity, include also the \*.rad.\* ones, they are just keywords so do not create any dependency on RAD and will make its life easier).

## Consequences

* Many users likely do some of this in their global eql transforms. If they combine their with Fulcro, they might end up with these props twice in the query, but that should not harm anything, since we get back just a map, so no duplication there
* Users will far less run into problems where tempid remapping does not work, b/c they used a mutation join and forgot to add :tempids
* Users will get pathom errors back by default, which will make it easier to discover what went wrong with their query/mutation

**Comment by awkay** [comment]
This is close to what we want (if we expand the default exclusion list):

```
(defn global-eql-transform
  "Returns an EQL transform that removes `(pred k)` keywords from network requests."
  [pred]
  (fn [ast]
    (let [mutation?     (symbol? (:dispatch-key ast))
          has-children? (seq (:children ast))]
      (cond-> (-> ast
                (rad-app/elide-ast-nodes pred)
                (update :children conj (eql/expr->ast :com.wsscode.pathom.core/errors)))
        (and mutation? (not has-children?)) (update :children conj (eql/expr->ast '*))
        mutation? (update :children conj (eql/expr->ast :tempids))))))
```

**Comment by holyjak** [comment]
Some questions, @awkay, to determine whether adding `::p/errors` anywhere to transactions with mutations is meaningful or not - because it seems that errors of a mutation itself is returned as `{<mutation-symbol> {::p/reader-error "some text"}}`.

1. Is it so that a "query" and a mutation is never combined in a single transaction / request to pathom, i.e. if the transaction contains a mutation, there are never any non-mutation top-level joins or properties - something like `[:x {:y [:z]} (mutation)]` will never happen and thus adding `::p/errors` to the top level is pointless?
2. Since mutation errors are returned as reader errors and are returned by default, we do not need to add anything to the transaction to get them in Fulcro

**Comment by awkay** [comment]
Honestly I do not remember/know. 

In terms of what needs to be in the query: remember that if there is a mutation join that Fulcro uses that for merge as well, so if the key is not in the outgoing query Fulcro itself will filter it.  

To be honest I'm torn on how much pathom-specific stuff to include, since that is an external lib that is in the process of changing how it works.  I'd probably tend to leave the pathom-specific keys out altogether and document that you might want to customize that part for your app.

**Comment by holyjak** [comment]
## No need for tempids?!

According to [my experiment](https://github.com/holyjak/minimalist-fulcro-template-backendless/commit/aed3d932697f0372edfaece582704a44b511c93c), we do not need to add `:tempids` to mutations:

1. If the mutation has no query then Pathom simply returns everything by default, thus including :tempids 
2. Even If I [add a query via m/returning](https://github.com/holyjak/minimalist-fulcro-template-backendless/commit/aed3d932697f0372edfaece582704a44b511c93c#diff-a6e425615e9f1f1237e983d0db5fe758877e5146f1a1c282a800bff1f9b7b1dcR15) - and the server-seen query becomes `[{(com.example.mutations/create-random-thing {:tmpid #fulcro/tempid["1b59713c-305c-4b8d-802d-7b39b8a4e696"]}) [:fake :com.wsscode.pathom.core/errors]}]` - still tempids are returned to Fulcro 

(Pathom 2.3.1, Fulcro 3.5.2)

**Comment by awkay** [comment]
Hm. I have seen this mess up in RAD, so I know it doesn't work through the stack. It could be that Fulcro's the one filtering the tempids?  Does the remap work in case (2)?

**Comment by holyjak** [comment]
It does. I will try this with RAD demo itself.

**Comment by holyjak** [comment]
Confirmed that in RAD Demo I need to add :tempids to mutation joins otherwise tempids are not returned  by Pathom. Need to explore.

**Comment by holyjak** [comment]
Oh, I see why getting back tempids worked in my first test. I had this in my parser config:

```clojure
{::p/env {::pc/mutation-join-globals [:tempids], ...}}
```

**Comment by awkay** [comment]
Yes, I was not aware of this option in Pathom. It would be better to just recommend that and fix the templates.

In terms of the errors: Fulcro does not require Pathom, and how you deal with errors on Pathom is also pretty configurable.  I'm fine with setting up the templates to glue together error handling in some "useful" manner but given that Pathom 3 might even change this key I really don't want to chase Pathom on this in Fulcro's code.

**Comment by holyjak** [comment]
Then I guess we should close this issue as "won't fix"?

**Comment by awkay** [comment]
Yeah, let's open up the templates and fix them, and also document it in the tempids section of the book.  Let's just track it with this issue, since all the history is here.
