### ISSUE TITLE
Mutations cannot properly return to-many results

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#490]
The requirement that tempids come in a map returned from the mutation means there is no way to return a vector AND tempids at the same time. The workaround is to modify the outgoing AST in the mutation remote env, and use ok-action to do the remaining work.

Other factors to consider:
* tempids in metadata only works with new versions of transit...older versions cannot transmit it that way
* Could add `returning-to-many` and handle rewriting the AST on the client and modifying the auto-merge facilities, but that requires the server mutation to cooperate (probably has to anyway...has to return a map with tempids and the result).

**Comment by sheluchin** [comment]
I ran into this issue when using a server mutation to generate new objects and save them to the backend db. I wanted to return a vector of maps containing the ids of the newly created objects and have the `remote` section in the client mutation append them to an existing list in the client db using mutation join and targeting helpers:

Server:
```clojure
(pc/defmutation import-notes [env params]
  ; ...
  [#:note {:id #uuid "cc01c445-5540-4241-ae3c-cdcfc93a18c0"}
   #:note {:id #uuid "7d3f53ee-92e1-45a2-9358-59e01f51734f"}])
```

Client:
```clojure
(defmutation import-notes
 [params]
 (action [{:keys [state]}] (log/info "Importing notes") state)
 (remote [env]
   (-> env
     (m/returning Note)
     (m/with-target (targeting/append-to [:note-list/id
                                          :singleton
                                          :note-list/notes])))))
```

The client db result was that a single nil item was added in two places:

At path `[:note/id]`:
```clojure
{3 {...},
 1 {...},
 2 {...}, 
 nil {}}
```

At path `[:note-list/id :singleton :note-list/notes]`:
```clojure
[[:note/id 3] [:note/id 1] [:note/id 2] [:note/id nil]]
```

**Comment by awkay** [comment]
There are other ways of dealing with this as well. For example the mutation going out can specify a query using the AST that focuses on any throw-away virtual edge and use a subquery to get normalized elements.  Adding targeting to that gets you a mutation that can return multiple things anywhere into the graph and should probably be considered the idiomatic solution to this problem.

```
(remote [env]
   (-> env
     (m/returning (rc/nc [:note-list/id {:note-list/notes [:note/id  :note/content]}])))
```

would allow the remote to return the targeted portion of the note list as a map:

```
{:note-list/id 42
 :note-list/notes [{:note/id 1 ...} ...]}
```

which would normalize correctly. The merge system of Fulcro does NOT ever overwrite things that are not queried for, so the note list would be unharmed except for it's list of notes.
