### ISSUE TITLE
Improve error messages when users supply bad data to normalization

### ISSUE THREAD

**Issue by holyjak** [fulcrologic/fulcro#491]
If the developer makes a mistake and thinks she is getting a vector of maps and tries makes a join for it in the query (which happens easily as the data model and componens evolve during the initial explorations) then init will blow up in a way that is hard to troubleshoot, with the error

```
Error: conj on a map takes map entries or seqables of map entries
    ...
    at cljs$core$merge (core.cljs:9131)
```

When I run the same code in Clojure, the error is much better:

```
Execution error (ClassCastException) at com.fulcrologic.fulcro.algorithms.normalize/normalize*$fn$fn (normalize.cljc:64) . 
class java.lang.Character cannot be cast to class java.util.Map$Entry
```

This happens with code such as:

```clojure
(defsc Tag [_ _]
  {:query [:tag/id :tag/desc]
   :ident  :tag/id
   :initial-state {}}
  (dom/p ""))

(defsc Menu [_ _]
  {:query         [{:tags (comp/get-query Tag)}] ; <-- WRONG, tags are strings not maps
   :ident         (fn [] [:component/id :Menu])
   :initial-state {}}
  (dom/p ""))

(defsc Root [_ _]
  {:query [{:task-filters (comp/get-query Menu)}]
   :initial-state (fn [_] {:task-filters  {:tags ["Important" "Urgent"]}})}
  (dom/p "root"))
```  

So what I would love is a better error message and **I would be happy to provide the code** to make it possible. However I guess I would need some guidance as the code in question:

https://github.com/fulcrologic/fulcro/blob/c840483be0c635825b47b8f6434c98de093bf83c/src/main/com/fulcrologic/fulcro/algorithms/normalize.cljc#L64

is quite hard to understand without enough "domain knowledge". One option would be to wrap it in a try catch:

```clojure
  (try
    (update-in m i merge x)
    (catch #?(:clj Exception :cljs :default) e
      (when-not (map? x)
        (throw (ex-info (str "Your query includes a join on an attribute whose value is a vector of non-maps: " v) 
                 {:data v, :k k, :class class, :q q})))
      (throw e)))
```

but there is surely a better solution. (I also obviously do not know which info is most helpful to include in the error message. Or rather where to get the name of the component with the incorrect query and the attribute that should not have a join.)

**Comment by awkay** [comment]
On second thought, how about this:

Leave `normalize*` alone, BUT wrap the use of it in a try/catch. If an exception is caught, THEN call a slower/more complex version that you write (which can have bugs, since it is just about error reporting) and have that report the problem.
