### ISSUE TITLE
Unnecessary re-rendering

### ISSUE THREAD

**Issue by simon-katz** [fulcrologic/fulcro#497]
Fulcro appears to be doing some unnecessary re-rendering that it didn't used to do.

I believe a bug was introduced in version 3.2.2. (No problem with 3.2.1-RC5, and there's no 3.2.1.) Version Fulcro 3.5.9-RC1 still has the problem.

I've been following the Fulcro video tutorials. The repository at https://github.com/simon-katz/fulcro-unnecessary-re-rendering (using Fulcro 3.5.9-RC1) is based on video 5 (How Rendering Works).

The video discusses how Fulcro avoids unnecessary re-rendering, and the rendering code includes logging.

When I invoke the `make-older` mutation:

- With Fulcro 3.2.1-RC5 things are as described in the video — only the changed Person component is re-rendered.

- With Fulcro 3.2.2, all parent components are also re-rendered.

**Comment by awkay** [comment]
I changed the default renderer some time back. The default now does root-based rendering by default (the optimization, when measured, doesn't actually do much and it makes UI harder to understand).  You can change the renderer back to ident-optimized-render to get the old behavior, but I dont 'generally recommend it.

**Comment by awkay** [comment]
https://clojurians-log.clojureverse.org/fulcro/2021-01-28/1611840793.088100-b for reference...though that doens't match your version findings, the behavior diff makes sense...perhaps the old slack message was wrong about the numbering.

**Comment by simon-katz** [comment]
Ah, OK. Thanks.
I'll add a comment to the video.
