### ISSUE TITLE
Denormalize should not "detect loop" for leaf entities

### ISSUE THREAD

**Issue by holyjak** [fulcrologic/fulcro#499]
Currently the loop detection in recursive queries produces **false positive** when the same leaf entity is used in multiple non-leaf entities, as shown below (the keywords are the IDs, nesting indicates parent-child relationship):

```
:Root
  |- :Leaf1
  \- :Non-leaf
       \- :Leaf1
```

Steps to reproduce:

```clojure
(def APP (app/fulcro-app)) 
(merge/merge!
    APP
    {:id {:Root     {:id :Root, :children [[:id :Non-leaf] [:id :Leaf]]}
          :Non-leaf {:id :Non-leaf, :children [[:id :Leaf]]}
          :Leaf     {:id :Leaf}}}
    '[*])
  
  (let [state (app/current-state APP)]
    (fdn/db->tree [{[:id :Root] [:id {:children '...}]}] 
      state state))
; => {[:id :Root] {:id :Root, :children [{:id :Non-leaf, :children []} {:id :Leaf}]}}  <- :Non-leaf's :children is missing :Leaf !!!
; [CONSOLE] WARN [denormalize:126] - Loop detected in data graph - we have already seen {:id :Leaf} 
; inside :children . Recursive query stopped. See https://book.fulcrologic.com/#warn-denormalize-loop-detected
```

(I am running the code from #498 so the error message is a little different from the released Fulcro)

## Proposed solution

At

https://github.com/fulcrologic/fulcro/blob/52d8d8aea63bea26304ee65d8004a0add4273b45/src/main/com/fulcrologic/fulcro/algorithms/denormalize.cljc#L102-L104

do not add the ident `v` if its entity has empty/nil children, i.e. (simplified, for to-one) skip adding it if `(and (not link-join?) is-ref? (not (get join-entity key)))`.

## Variant: Repeated subtrees

We can encounter a situation where the `:Leaf` node has actually children of its own, i.e. is the root of a subtree, but this whole subtree is kind of a "leaf" and is not on the recursive path. We would still detect it as a loop though practically there is no loop there.

The big question is whether it is worth doing something about it. How common is the situation? And there is a feasible workaround: Set (a large) limit on the recursion depth.

**Comment by awkay** [comment]
Is there a workaround that works right now??? Does an explicit depth limit work?

**Comment by holyjak** [comment]
Closing this issue as there is a well-known workaround (and, as Tony suggested, "every program I've seen using recursion this way is usually better off written differently").
