### ISSUE TITLE
`comp/get-query` not correct when using raw component and union query

### ISSUE THREAD

**Issue by dmcgillen** [fulcrologic/fulcro#515]
I'm attempting to use a union query and have something working with components created with `defsc`, but I'd like to instead use raw components because I need something more dynamic (I'm going to be using this for error handling, the below is just a made up example). I've found that the query returned when using raw components with a union isn't quite what I'm expecting (which means the required parent component that joins my union isn't right).

Here is a simple example that works when using `defsc`.

```clj
(defsc Person
  [_ _]
  {:query [:person/id :person/name]
   :ident :person/id})

(defsc Place
  [_ _]
  {:query [:place/id :place/name]
   :ident :place/id})

(defsc PersonOrPlaceUnion
  [_ _]
  {:query (fn []
            {:person/id (comp/get-query Person)
             :place/id (comp/get-query Place)})
   :ident (fn [_ props]
            (if (contains? props :person/id)
              [:person/id (:person/id props)]
              [:place/id (:place/id props)]))})

(comp/get-query PersonOrPlaceUnion)

; => {:person/id [:person/id :person/name], :place/id [:place/id :place/name]}
```

When I use a raw component, however:

```clj
(def PersonOrPlaceUnionRawComponent
  (rc/nc
   {:person/id (comp/get-query Person)
    :place/id (comp/get-query Place)}
   {:componentName :person-or-place/component
    :ident (fn [_ props]
             (if (contains? props :person/id)
               [:person/id (:person/id props)]
               [:place/id (:place/id props)]))}))

(comp/get-query PersonOrPlaceUnionRawComponent)

; => [[:person/id [:person/id :person/name]] [:place/id [:place/id :place/name]]]
```

Notice the difference in the output of `comp/get-query`.

**Comment by awkay** [comment]
Ah, you're, the rc function always assumes it is a normal component

**Comment by awkay** [comment]
Try 3.5.20-SNAPSHOT. I wrote tests for the top-level case you're  doing and fixed the code, so it should work in this case.  I did not test the case where a union is nested more deeply in the structure of nc, though an explicit call to `nc` on the union should always work.

Let me know.

**Comment by awkay** [comment]
Commit 5c0fe4931e1872d6f58c713997f19430498a07ee

**Comment by dmcgillen** [comment]
Thanks for the quick response, this appears to do the trick :+1:
