### ISSUE TITLE
Fulcro 3.6 use of React Context breaks shouldComponentUpdate optimizations

### ISSUE THREAD

**Issue by rynkowsg** [fulcrologic/fulcro#526]
I've been following the Fulcro video tutorials. The video 5 (How Rendering Works) discusses how Fulcro do re-rendering, and the rendering code includes logging. With `:optimized-render! keyframe/render!` Fulcro should re-render only the component that changed with its parents.

Fulcro 3.6.0-RC3 with `:optimized-render! keyframe/render!` appears to be re-rendering everything on every mutation. Not only parents components, everything basically. Have a look at the screenshots below.

In contrary Fulcro 3.5.34 with React 17 works as expected.

| fulcro 3.5 + React 17 | fulcro 3.6 + React 17 | fulcro 3.6 + React 18 |
| --- | --- | --- |
| ![Screenshot 2023-01-13 at 01 01 14](https://user-images.githubusercontent.com/5878299/212212994-16c5f307-329f-4a24-bc99-9badee20ee5c.png) | ![Screenshot 2023-01-13 at 01 15 15](https://user-images.githubusercontent.com/5878299/212214624-dec98dea-7c6c-46ea-9523-a4daf16d277c.png) | ![Screenshot 2023-01-13 at 00 55 06](https://user-images.githubusercontent.com/5878299/212212867-5626e4d9-3ca5-4bb6-83de-91061d4db0ae.png) |

The repository at https://github.com/rynkowsg/fulcro3-yt-tutorial/ is based on video 5 (How Rendering Works).
These commits reflect effects shown on the screenshots:

- [d554d8b](https://github.com/rynkowsg/fulcro3-yt-tutorial/commit/d554d8b) - Fulcro 3.6.0-RC3 with React 18
- [b973d1c](https://github.com/rynkowsg/fulcro3-yt-tutorial/commit/b973d1c) - Fulcro 3.6.0-RC3 with React 17
- [2922d4e](https://github.com/rynkowsg/fulcro3-yt-tutorial/commit/2922d4e) - Fulcro 3.5.34. with React 17 (works as expected)

**Comment by awkay** [comment]
Ah, there is a rendering optimization in 3.6 that is causing this behavior, but I may have done it wrong. The old system always checked props on root in shouldComponentUpdate, which is a huge waste of CPU particularly for deep and wide trees, since you'll spend more time on the compare than the render in most cases. So I made the default skip the check on root.  The side-branches, however, should still have their SCU in tact, and should short-circuit. I'll have a look. Thanks for pointing it out.

**Comment by awkay** [comment]
Argh...Yeah, this is broken. Very sad.  The SCU function is fine. I had to switch to using React context to pass various things down the tree (was using dyn vars but async render nixed that)...unfortunately when the context changes, the components all re-render and SCU is ignored (though still called, annoyingly enough).

I'll have to hack some more and see what I can figure out.

**Comment by awkay** [comment]
I think this is fixed in 3.6.0-RC4-SNAPSHOT (sha 63f32e488ae02a94e6172cfddb7e2d553897cca6). I need to test it more widely, but it fixes your example. Thanks for the report.

**Comment by rynkowsg** [comment]
I run it again with React 18 and 3.6.0-RC4-SNAPSHOT, and this time it fails to mount the APP.

![Screenshot 2023-01-13 at 11 07 07](https://user-images.githubusercontent.com/5878299/212306261-4e899d82-39b4-4783-8b4a-545b8d16f431.png)

The only [changes I introduced this time](https://github.com/rynkowsg/fulcro3-yt-tutorial/commit/7b0f4c04f94b798d5468d1ed4657714ce9dc76d3) were an update of React to 18 & upgrade to Fulcro 3.6.0-RC4-SNAPSHOT.

The reproducible setup is available here:
- repo: https://github.com/rynkowsg/fulcro3-yt-tutorial/ 
- branch: `230113-try-fulcro-rc4`
- commit: [`7b0f4c0`](https://github.com/rynkowsg/fulcro3-yt-tutorial/commit/7b0f4c04f94b798d5468d1ed4657714ce9dc76d3)

**Comment by awkay** [comment]
Pushed a new snapshot. It totally works with my setup, so I'm confused, but I change a macro and that seems to ahve cleared it up. 

SHA e06309b782f9e7ea91434580271fce02c0bcd773.

There is still one more thing to clean up, but that should behave better.

**Comment by awkay** [comment]
Looks like I'm not quite done. Hot code reload force refresh isn't working right now :(

**Comment by rynkowsg** [comment]
Is "Hot code reload force refresh" something different from "Hot code reload" (the refresh of the app on saving the file without losing the app state)?

I tested fulcro SHA 2b96c84 and it works fine, including hot code reload - _(fulcro3-yt-tutorial in [`4979e5c`](https://github.com/rynkowsg/fulcro3-yt-tutorial/commit/4979e5c))_ .

**Comment by rynkowsg** [comment]
I think the issue this ticket was opened with originally is solved now. It probably can be closed now.

**Comment by awkay** [comment]
I need to verify that my fix didn't break anything else, then I'll cut an official RC
