### ISSUE TITLE
FormatJS Custom Formats

### ISSUE THREAD

**Issue by OscarMarshall** [fulcrologic/fulcro#53]
In the Fulcro devcards it's mentioned how FormatJS is extensible; however, I don't see any way to pass a formats object to MessageFormat. As I understand it, the MessageFormat constructor can take the formats object as the third parameter, but `fulcro.i18n/trf` is hardcoded to [only pass two](https://github.com/fulcrologic/fulcro/blob/develop/src/main/fulcro/i18n.cljc#L58). Could we get an option in `new-fulcro-client` or an atom in `fulcro.i18n` where we can set custom formats?

**Comment by awkay** [comment]
You are correct. The atom solution is probably the one that will work best...`trf` doesn't have any connection to the client itself (to make it as lightweight and non-intrusive as possible), so the i18n in general is hooked to globals (translations and current locale).

**Comment by awkay** [comment]
One issue is that SSR uses these as well, which means that the code to add them has to somehow work with ICU4J. I think this is why I didn't add them. Needs more research. For now, I can add a hook that works on the JS side only.

**Comment by awkay** [comment]
Added in 1924df9e8c77126945a61f0a87c9bd427f46f04d

Pushed to 1.1.0-SNAPSHOT on clojars. Please test and confirm it is what you're looking for.
