### ISSUE TITLE
Potentially add "Accept: application/transit+json" header.

### ISSUE THREAD

**Issue by tommy-mor** [fulcrologic/fulcro#531]
https://github.com/fulcrologic/fulcro/blob/18c27e5ddb694763e03f846bda8582d8eb749822/src/main/com/fulcrologic/fulcro/networking/http_remote.cljs#L142

The twin handler also assumes/only works with transit. This tripped me up because muuntaja saw the default "Accept: */*" header in the request and returned json. I think that "Accept: */*" can be argued to be a wrong header, because the my handler (the default fulcro one) only accepts transit.

I know fulcro is not tied to transit, but I think this is a reasonable default to add. Especially because this fails quietly when you use muuntaja, another popular clojure library which handles content negotiation

**Comment by awkay** [comment]
I'm open to fixing this, but I'm not sure what you're suggesting exactly. Can you make a PR, or type the change your sugggesting?
