### ISSUE TITLE
Potentially omitted :force-root in `schedule-render!`

### ISSUE THREAD

**Issue by rynkowsg** [fulcrologic/fulcro#536]
I've been working with i18n library recently, and I noticed that the root is re-rendered twice (when translations has been already fetched) or even three times (if has not been fetched yet). I tried to find solution to this and I found potential bug in _schedule-render!_.
Please verify whether my reasoning is correct. I'm still new to fulcro so I might be missing something.

#### Root double rendering when using i18n

From what I understand multiple rendering of the Root when using i18n happens due to calling render on two or three occasions:
- `(schedule-render! app)`  from [process-queue!]
- `(render! app {:force-root? true})`  ([app/force-root-render!]) from [i18n/change-locale] and optionally from [i18n/translations-loaded] (the latter is when we experience three re-renders)
- `(render! app {:force-root? true})`  ([app/force-root-render!]) from i18n/translations-loaded (this is the case when translations are missing and we need to fetch them)

(The behavior I expected was to see one refresh or two when fetch happen).

[process-queue!]: https://github.com/fulcrologic/fulcro/blob/608422c7eb600ed30b1a9d83a5a43a8f2af96ac9/src/main/com/fulcrologic/fulcro/algorithms/tx_processing/batched_processing.cljc#L780
[app/force-root-render!]: https://github.com/fulcrologic/fulcro/blob/608422c7eb600ed30b1a9d83a5a43a8f2af96ac9/src/main/com/fulcrologic/fulcro/application.cljc#L383
[i18n/change-locale]: https://github.com/fulcrologic/fulcro-i18n/blob/main/src/main/com/fulcrologic/fulcro_i18n/i18n.cljc#L82
[i18n/translations-loaded]: https://github.com/fulcrologic/fulcro-i18n/blob/main/src/main/com/fulcrologic/fulcro_i18n/i18n.cljc#L59

#### Potential solution

Initially I thought I could fix it by correcting i18n library, but then I realized it is fulcro thing. Ideal solution would be to use in [app/force-root-render!]
`(schedule-render! app {:force-root? true})`  (because it is debounced)
instead of
`(render! app {:force-root? true})`
And it works, but there is a...

#### <div id="problem-schedule-render">Problem with `schedule-render!`</div>

_schedule-render!_ and _render!_ render Root independently. Since _schedule-render!_ is debounced, it would avoid unnecessary rendering. The problem with the debouncing mechanism there is that it is a simple mechanism without interpreting what it gets - it honor only the last call. E.g. for the given chain of calls
```clj
(schedule-render! app {:force-root? false})
(schedule-render! app {:force-root? true})
(schedule-render! app {:force-root? false})
```
it is going to call only the last one ([debounce impl](https://github.com/google/closure-library/blob/master/closure/goog/functions/functions.js#L474)).

In other words, :force-root true is not guaranteed when run with schedule-render!. In most of the cases works fine, but occasionally when debounce filters out some of fn calls, the call with :force-root true might be omitted.

#### Solution

The quick solution would be to create wrap two separate debounced fn within schedule-render!: one for calls with and without force-root true. It will not fix my issue with i18n and duplicated rendering but will fix the risk of omitting :force-root.

The better solution could be replacing this debounce with custom debounce[^1] fn smart enough to understand when to ignore timeout and run certain calls immediately. That should fix all, both double rendering and risk of omitting schedule-render! _:force-root true_.

[^1]: Alternatively we could use custom throttle-last.

**Comment by rynkowsg** [comment]
Another observations, aren't `debounce` and `sched/schedule-animation!` overlapping functionality. At the first glance `sched/schedule-animation!` looks like throttle-first with a global state.
```
(debounce (throttle-first (fn [] ...) 16) 16)
```
Since the debounce encapsules _sched/schedule-animation!_, the latter is not going to do anything, unless _sched/schedule-animation!_ with that particular action is also used somewhere else.

**Comment by awkay** [comment]
Your problem report is not clear to me. Are you observing a condition where the UI is incorrect? Or are you reporting that you don't like it that render might be called more than you like?

**Comment by rynkowsg** [comment]
This issue is not about double rendering (which was initial reason for my investigation) but about shared props not being recalculated under certain conditions.

Please have a look at issue desc under section titled [Problem with schedule-render!](https://github.com/fulcrologic/fulcro/issues/536#user-content-problem-schedule-render). I haven't try to reproduce it, but by reading the code, it looks that **calling `(schedule-render! app {:force-root? true})` is not guaranteed to honor :force-root?** true, meaning **when we request force shared props to be recalculated, under certain conditions they might not get recalculated**.

It is not my problem, but if I'm correct, it is a source of occasional issues related to shared props. 

I don't have certainty that this is a problem, that is why I opened the issue to report it and listen what you say.

**Comment by rynkowsg** [comment]
In other words:
- `(render! app {:force-root? true})` - recalculates shared props always
- `(schedule-render! app {:force-root? true})` - most times recalculates shared props, sometimes not

**Comment by awkay** [comment]
Thanks for the clarification. Your final message was much more consumer-friendly. Succinct and to the point is best.

I agree with your assessment. Schedule render will not accumulate options which will cause a forced-root to be missed. That said, a force root render really should only be used in two cases I can think of: ops like i18n change locale where props have not changed but re-render is necessary, and dev-time.

the i18n code should therefore do a manual render and not a scheduled one.
