### ISSUE TITLE
Any interest to try shadow-cljs as the build tool

### ISSUE THREAD

**Issue by jiyinyiyong** [fulcrologic/fulcro#54]
[shadow-cljs](https://github.com/thheller/shadow-cljs) is another tool for developing and bundling ClojureScript. There are several features related to the GettingStarted document:

* compile the code
* hot code swapping
* serving HTML and assets files
* REPL to connect to the running environment

To define a compilation like https://github.com/fulcrologic/fulcro/blob/develop/GettingStarted.adoc#11-project-file , it's uses a file called `shadow-cljs.edn`:

```edn
{:source-paths #{"src/main" "src/dev"}
 :dependencies [[org.clojure/clojure "1.9.0-alpha17"]
                 [org.clojure/clojurescript "1.9.908"]
                 [org.omcljs/om "1.0.0-beta1"]
                 [fulcrologic/fulcro "1.0.0-beta10"]]
 :builds {:dev {:target :browser
                :output-to "resources/app/js/app.js"
                :output-dir "resources/app/js/app"
                :main cljs.user
                :asset-path "js/app"
                :devtools {:after-load cljs.user/refresh
                           :preloads [devtools.preloads]}}}}
```

Fields look similar to the one in Lein. But it's shorter to write since it's designed for compiling ClojureScript only. Many of the dependencies have already been built into shadow-cljs.

To start running shadow-cljs, you will need Node.js :

```bash
yarn add --dev shadow-cljs
yarn shadow-cljs watch dev # watch for development, dev for :build-id
```

It's started with a command line, so no need to add another script. As the watch server started, you get hot code swapping from `:devtools` configs.

If you need a REPL for connected environment, try:

```bash
yarn shadow-cljs cljs-repl dev
```

After you got an HTML, to serve the files, it's [built in](https://github.com/thheller/shadow-cljs/issues/128#issuecomment-342553347) shadow-cljs. Just add configs in `:devtools` configs:

```edn
:http-root "public"
:http-port 8020
```

and you will get an HTTP server serving `public/` at `http://localhost:8020`.

I guess shadow-cljs can be faster, since it's designed for ClojureScript specifically. But it may be used together with lein too.

Besides, shadow-cljs brings some improvements to cljs development too, like CommonJS support, more work on externs, filename hashing, dynamic loading, etc. It brought me a lot of useful features. I hope it may help in your scenarios too.

**Comment by awkay** [comment]
Hi, thanks for the notes. I've been pondering it, especially since it seems like the module support might be better (for now at least).  At the moment I have too many things going on to even play with such a change, but would welcome a contribution. Perhaps you'd like to add an option to the lein fulcro template?

Closing this here, feel free to issue a PR against fulcro-lein-template to support the option.

**Comment by jiyinyiyong** [comment]
No indention to create a lein-template currently. If you would like to give it a spin, I have a template for myself, based on shadow-cljs, which has beed iterated for months, maybe it will help https://github.com/mvc-works/coworkflow/blob/master/shadow-cljs.edn . It's not based on Om, but the shadow-cljs part should be the same.
