### ISSUE TITLE
dr/change-route-relative! -- denied route does not call :route-denied component option

### ISSUE THREAD

**Issue by jmurp** [fulcrologic/fulcro#540]
`change-route-relative!` does not trigger the :route-denied function defined on the target component

The call in this function after `(not (can-change-route? app-or-comp relative-class))` evaluates to true: `(target-denying-route-changes app)` returns a null target even though a target did deny the route. I think this line should be: `(target-denying-route-changes app relative-class)` because this seems to works in my case. I have multiple on screen routers.

**Comment by awkay** [comment]
Fixed in 3.6.4
