### ISSUE TITLE
fs/dirty-fields misses recursive field

### ISSUE THREAD

**Issue by jmurp** [fulcrologic/fulcro#542]
I have a component with a recursive field that is also a form-field.
fs/dirty-fields always gives a nil entry for this field regardless of its value in the database.
The recursion limit is 1, but I get the same result with the '... recursion notation. (I am using the lambda notation for :query)
When I use a duplicate component instead of using recursion, fs/dirty-fields works.  That is my current work-around.

**Comment by awkay** [comment]
It is probably true that form-state doesn't work on recursive queries, and that making explicit recursive versions is the workaround. I'd be happy to see a PR if you want to dig into it, but it is such a corner case that it is not something I will be working on.
