### ISSUE TITLE
Issue with use-statechart hook

### ISSUE THREAD

**Issue by yenda** [fulcrologic/fulcro#553]
This changeset caused an issue with the statechart library:  https://github.com/fulcrologic/fulcro/compare/6401d60f0d3c7a1f8f135dace1ed80868cc28aea...ec78647d1a986ada6fa7123f70b1ce79fb5ee56d

The issue is that after a component that uses `use-statechart` is unmounted, the error: `apply-route* was called without a proper :router argument` occurs followed by multiple errors and obviously the routing not happening.
This is because `use-statechart` uses `use-gc` which is using `remove-entity` and is therefore affected by the changeset.

The particular line that is causing issue is:
`(vector? ele) (filterv #(not= ident %) ele)`
When I remove it the bug disappears, when I add it back it comes again.
I couldn't figure out why at this point. 
In my case the state before and after `remove-leftover` is the "same", as in if I put the output of the `reduce` in a let binding then compare `(= before after)` it is `true`. But if I return `before`: no bug, if I return `after`: bug.
My assumption was initially a vector vs list discrepency because `(= '(1 2 3) [1 2 3])` is `true` but I couldn't verify it.

**Comment by awkay** [comment]
Fixed
