### ISSUE TITLE
Regression in forms

### ISSUE THREAD

**Issue by yenda** [fulcrologic/fulcro#554]
Since that commit, when the form becomes dirty, the identities in subforms turn into nils and these changes can't be cancelled. as a result when saving the form the values of the subforms end up in the delta with the after being a vector of `nils`. (which for me means all items were deleted)

https://github.com/fulcrologic/fulcro/commit/5392b484517216abb6d26f9fb17f326b135d0f24

actually the tests started to fail
https://app.circleci.com/pipelines/github/fulcrologic/fulcro/852/workflows/3a0d1d55-8335-45f3-99cd-1f86866f71c8/jobs/3789?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

**Comment by awkay** [comment]
I fixed that problem in later versions, and those tests were already passing again.

I did, however, make an API change that evidently was not 100% bw compatible, so I've pushed a snapshot that makes the API change in a more compatible way, and that should fix it.

I am interested: Are you using remove-entity yourself, or are you speaking of just the interaction with normal form-state?

**Comment by awkay** [comment]
Released 3.7.10

**Comment by yenda** [comment]
I haven't found the time to test the latest commit yet, but the cause was an entity picker which has the use-gc hook
