### ISSUE TITLE
2.0 : Query Performance Optimization - Part 1

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#73]
The `add-basis-time` function in fulcro.client.primitives could cause performance problems in some apps. 

The purpose of this alg is to add meta-data timestamps on all maps that were queried for. At the moment, it uses prewalk, and *does not stop where the query stops*. 

One might be able to make it faster simply by choosing to use transients or specter.

The more aggressive optimization would be to give it the query that goes with the props, so you can stop recursion when the query stops. This is a slightly more complex algorithm (handling queries...recursion and unions), but it is also where the current algorithm falls down for some people. 

If you have an app that returns a boat load of data in a map, and you query for it like this: `[:my-boat-load]`, then there is only a need for the time metadata on the top-level map (not anything nested, because it wasn't part of the query or normalization). 

Such an application could suffer serious UI lag if that opaque data was rather large, and rapid UI refreshes were needed against it.

**Comment by wilkerlucio** [comment]
I'm going to add Fulcro 2.0 in a big app that has this situation (big map, query only for the root of it). So I'll probably try to do some work related to this soon.

**Comment by awkay** [comment]
This break the following demo:

http://localhost:8081/demos.html#!/cards.UI_router_as_list_with_item_editor/list-and-editor

seems it isn't doing it right for unions
