### ISSUE TITLE
Fulcro 2.0 Namespaces

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#75]
I've had to rename the imported namespaces from Om Next. I renamed them for the following reasons:

1. I’m hoping to be able to use git to roll Om Next history for that file (and dom) into mine. This will also let me follow bug fixes more easily). It also gives contributors there better credit.
2. The functions in next.cljc are at the edge of the dependency graph. The ones at core are not. Trying to move them into core puts them higher up, and would force me to make more API renaming changes in order to resolve circular dependencies (core refers to networking, which refers to primitives…if primitives moved into core: core would refer to networking would refer to core. This is true of a *number* of the namespaces…it becomes a real spider’s web)
3. Large files take a long time to compile. The more I jam into a single file, the worse incremental update compile times I get when working on the library
If anything I’d love to bust the thing up and move code that isn’t needed as public API to another file to improve the (incremental) compile time.
4. The name `next.cljc` is a misnomer for Fulcro…the functions there are the low-level API that Fulcro builds upon. `primitives` seems a good choice. I’d be open to suggestions. That one is the best I could come up with given the nature of them + a thesaurus

There are some existing other renames that I'm tempted by, but at the moment the renames I've done are easy to accomplish on a project using a simple script. Further namespace movement will make porting harder.

The primary problem is that some of Fulcro's add-ons require things that Fulcro defines, so code motion easily creates circular dependencies that could be quite invasive.

Some examples (off the top of my head):
1. Move InitiailAppState -> primitives
2. Move defsc -> primitives   (this might be circular)
3. rename fulcro.client.core -> fulcro.client (mirrors server)

I'd be very interested in hearing thoughts:

1. Do you *mind* having to port namespaces a bit more manually for a limited number of well-known things?
2. What suggestions do you have for things that have bad names?

**Comment by chrismurrph** [comment]
I always prefer good/granular namespaces. The act of manually moving things around will increase the understanding and is something I would like to do. When a namespace is referred to by a lot of other namespaces, but refers to few or none itself I tend to name it util/s or domain, with domain being for abstract stuff. So here primitives <=> domain I guess. The name primitives seems good to me.

**Comment by wilkerlucio** [comment]
I like having to import fewer namespaces, I much rather prefer a single namespace with most of the primitives than having to import multiple ones for the same base stuff. So I think would be interesting to have `defui`, `defsc`, `initial-state` all in the same namespace, because they are almost always used together.

**Comment by awkay** [comment]
See the CHANGELOG. Done in alpha7
