### ISSUE TITLE
the websockets component should support more than easy-server

### ISSUE THREAD

**Issue by gzll** [fulcrologic/fulcro#77]
when I added the websockets component into the system, get an error:
```
ExceptionInfo Missing dependency :handler of fulcro.websockets.components.channel_server.ChannelServer expected in system at :handler  clojure.core/ex-info (core.clj:4739)
```
https://github.com/fulcrologic/fulcro/blob/develop/src/main/fulcro/websockets/components/channel_server.clj#L134
ChannelServer needs a handler dependency.

**Comment by awkay** [comment]
I've pushed a slight improvement to 1.2.1-SNAPSHOT that allows you to use the websocket support from any ring handler. There is a demo at https://github.com/fulcrologic/websocket-demo

Needs documentation and more testing, and an example of use with a modular server.

**Comment by awkay** [comment]
Finished this with a full chat demo.
