### ISSUE TITLE
Initialize data loaded from remote

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro#83]
Currently we have a gap regarding data loading + init state, when we start combining elements that need `:ui/...` data + data load, we need to write some manual post-mutations to get the data from the server and add the initial state. This requires manual updating the database after the data loads, and as the component dependency gets bigger this gets more and more complex.

I have a suggestion of an implementation that can mitigate this issue:

```clojure
(defn merge-entity [state x data & named-parameters]
  "Starting from a denormalized entity map, normalizes using class x.
   It assumes the entity is going to be normalized too, then get all
   normalized data and merge back into the app state and idents."
  (let [idents     (-> (om/tree->db
                         (reify
                           om/IQuery
                           (query [_] [{::root (om/get-query x)}]))
                         {::root data} true)
                       (dissoc ::root ::om/tables))
        root-ident (om/ident x data)
        state      (merge-with (partial merge-with merge) state idents)]
    (if (seq named-parameters)
      (apply fulcro/integrate-ident state root-ident named-parameters)
      state)))

(defn init-state
  "Starting from an ident and query, scan the DB initializing the components. This should be used to initialize data
  loaded from the network with fulcro fetch, this will recursively traverse using query information and merge the
  initial state with the current data (data load from the server takes priority)."
  ([state x ident]
   (let [initial  (fulcro/get-initial-state x nil)
         children (-> x om/get-query om/query->ast :children)
         data     (om/db->tree (om/get-query x) (get-in state ident) state)]
     (reduce
       (fn [s {:keys [type component key]}]
         (if (and (= :join type) component)
           (let [value (get-in state (conj ident key))]
             (cond
               (om-ident? value)
               (init-state s component value)

               (vector? value)
               (reduce
                 (fn [s ident]
                   (if (om-ident? ident)
                     (init-state s component ident)
                     s))
                 s
                 value)

               :else
               s))
           s))
       (merge-entity state x (merge initial data))
       children))))
```

The previous algorithm works with a class and an ident. It will start generating the data from that class and merging it back on the given ident (the data loaded before takes precedence, so only new keys are added). After doing it on the first level it traverses the relations that are there (don't create new entities on this step) and initialize then, until it finishes.

This can be integrated on data load, I think it could be another option to load, like `{:init-data true}`.

**Comment by wilkerlucio** [comment]
I was thinking about this today and occurred to me that the `normalization` step might be a good place to handle this. What if we have a `:initialize` flag on the `load` operations, and when it's on, Fulcro would just merge the initial component state with the loaded state (giving higher precedence to the loaded data).

Just to clarify, right now Fulcro does a great job with the initial state when the app is initialized, but when load data we also need to initialize the components (especially for `ui` properties). So I suggest we can do that with the normalization process. What do you think?

**Comment by awkay** [comment]
Not sure why you can't just use destructuring defaults for this concern?

**Comment by wilkerlucio** [comment]
For example, I have a component that generates random data to ensure the user input, I can't generate this every time, I have to generate once and keep that as part of the state for later. And there are more complicated cases where a component needs to initialize sub-components, for those, there is no way to use default props.

**Comment by awkay** [comment]
I still don't agree on that...why can't the subcomponents use defaults in their destructuring?

Also, implementation-wise: initial state goes deep...what if you have this:

Loading X with child A. X is present, A is *not*. `:initialize true`. What do I do? Do I initialize A? Do I skip re-initializing X (even though that's technically what I loaded)?  What, do a recursive check via the query or something to see what *might* be coming in? It's a mess of complication. 

The fact that you want to use generators seems to be the issue. Your data isn't stable. I'm not really interested in adding a complicated feature whose primary role is to support non-production data generators that happen to change every time.

\WeI need something more compelling than that I think.

**Comment by awkay** [comment]
@wilkerlucio are you still interested in discussing this? If not, let's close it.

**Comment by wilkerlucio** [comment]
Yes, I wanna give some real example, just didn't had the time yet, probably on the weekend.

**Comment by wilkerlucio** [comment]
After thinking a lot about it, I tried to create this small example so we can discuss around it:

```clojure
(fp/defsc ComplexUI [this props]
  {:initial-state {:ui/id           (random-uuid)
                   :ui/confirm-code (rand-int 10000)}
   :ident         [:ui/id :ui/id]
   :query         [:ui/id :ui/confirm-code]})

(fp/defsc Card [this props]
  {:initial-state {:ui/complex-ui {}}
   :ident         [:card/id :card/id]
   :query         [:card/id :card/number
                   {:ui/complex-ui (fp/get-query ComplexUI)}]})
```

Given the code above, let's trigger an example load for it:

```clojure
(fetch/load reconciler :app/main-card Card)
```

And server responds with:

```clojure
{:app/main-card {:card/id 123
                 :card/number 333}}
```

At this point, we can expect the db state to be:

```clojure
{:app/main-card [:card/id 123]
 :card/id       {123 {:card/id     123
                      :card/number 333}}}
```

The problem is, what about the `ComplexUI` entity? This is not at all on the DB, and by lacking it data, all behavior from it will break. And keep in mind that `ComplexUI` can be way more complex than that, it might require it's own child components for UI reasons.

So in the end, the only way to proper initialize it is to create a `post-mutation` and manually do the initialization for every sub-ui that needs it.

I think we can solve this problem on the fulcro side. During the normalization process, if just before normalizing we do a merge of the component initial state with the loaded data and then normalize, it can work. Using our example again to illustrate, this is what should happen:

Given the response from the server:

```clojure
; state from server
{:app/main-card {:card/id 123
                 :card/number 333}}

; component initial state
{:ui/complex-ui {:ui/id #uuid "6fc1dae7-05c2-45ed-b235-09ce2d9b951b"
                 :ui/confirm-code 3415}}

; merging it, of couse, we need to unwrap from :app/main-card, but then
(merge initial-state loaded-data)
; results in:
{:app/main-card {:card/id       123
                 :card/number   333
                 :ui/complex-ui {:ui/id           #uuid "6fc1dae7-05c2-45ed-b235-09ce2d9b951b"
                                 :ui/confirm-code 3415}}}

; now, normalizing from there:
{:app/main-card [:card/id 123]
 :card/id       {123 {:card/id       123
                      :card/number   333
                      :ui/complex-ui [:ui/id #uuid "6fc1dae7-05c2-45ed-b235-09ce2d9b951b"]}}
 :ui/id         {:ui/id           #uuid "6fc1dae7-05c2-45ed-b235-09ce2d9b951b"
                 :ui/confirm-code 3415}}
```

By merging like that, we ensure the loaded data is kept intact, but any missing data (compared to initial state) will be filled in, ensuring that the component is properly initialized.

What you think?

**Comment by awkay** [comment]
So I've understood your intent from the beginning. My problem with it is more around clear API. Initial state was meant for the initial startup state of the application. That is a specific and distinct phase of the application's lifecycle, and the needs that you have at that time can be significantly different from the needs at later times once the application is in operation.

For example, you might not want there to be initial state in some sub-tree, but you want this functionality you speak of later. If you compose it in you would have to possible write code that complects the nature of the function over two different (though related) aspects of your program.

This is always a temptation: convenience and minimal feature set (re-use initial-state for a related thing) vs. use an alternate (e.g. post mutations) which might give a clearer purpose at the expense of a little extra code.

Given that you can share code rather easily, what you're really asking is "can I save typing a few mutations and helper functions".

As it stands, a simple function

```
(defn make-complex-ui [..])
(defn init-ui* [state ...} (make-complex-ui ...))

(defui ComplexUI [t p]
  :initial-state (fn [params] (make-complex-ui params)))

(defmutation init-ui [params]
  (action [{:keys [state]}] 
    (swap! state (fn [s]
       (->s (merge-component ComplexUI (get-initial-state ComplexUI)
               (integrate-ident ...))))
...

(load this :x V {:post-mutation `init-ui})
...
```

Now, on first look, I've got a bit more code. It's not a *lot* of code. There would be a little merge (logic (easily doable via Fulcro merge calls). Technically, you could even use `get-initial-state` to pull the tree, then normalize and merge it with `merge-component`...so it is trivial to write the `init-ui` mutation.

In fact, this kind of generic sugar would be easy to auto-generate through macros as well.

So, the separation of concerns is not terribly hard to get with what we already have.

I'm not really willing to *by default* complect initial startup state with merge logic. I think it is a bad idea. However, I would entertain the idea of adding an *option* to `load` that would let you indicate that you want to do that. 

So, perhaps we add an `initialize` option that, when true, does your behavior. That way you could write a simple wrapper function to "default" it to true if you always want it, but the default could be false to preserve the default separation of concerns.

**Comment by awkay** [comment]
I opened a feature branch for this in issue-83. I'll think about it a bit more, and see if it is clean to do it. I think some validation will be in order...certain combinations are required:

- The component must be supplied
- The component must have a query
- The component must have initial state
- Deep merge has to make sense for it...definitely going to feel a bit like an experimental feature until we've played with it a bit.

**Comment by awkay** [comment]
So, here's what I'm trying:

- `:initialize true` means use `(get-initial-state Component {})`
- `:initialize {:z 1}` means `(get-initial-state Component {:z 1})`

I could also rewrite it so if you pass a map it is literally the component's value for initial state...that way you could manually say `:initialize (get-initial-state Component {})` yourself...

Thoughts?

**Comment by awkay** [comment]
PR-106, once merged, fixes this issue.

**Comment by awkay** [comment]
Merged.
